import fs from "node:fs";
import test from "node:test";
import assert from "node:assert/strict";
import { orderedGalleryServices, promotionForService, resolveGalleryCopy } from "../src/utils/galleryPresentation.js";

const gallery=fs.readFileSync("src/components/GalleryCarousel/GalleryCarousel.jsx","utf8");
const page=fs.readFileSync("src/pages/Gallery.jsx","utf8");
const admin=fs.readFileSync("src/pages/AdminGallery.jsx","utf8");
const migration=fs.readFileSync("supabase/migrations/20260804700000_gallery_media_multiple_services.sql","utf8");
const eyelashMigration=fs.readFileSync("supabase/migrations/20260910100000_add_design_com_henna_to_eyelash_gallery_media.sql","utf8");
const correctionMigration=fs.readFileSync("supabase/migrations/20260910120000_correct_gallery_service_associations.sql","utf8");
const services=[{dbId:1,id:11,title:"Design",description:"Descrição principal",active:true},{dbId:2,id:12,title:"Henna",description:"Descrição henna",active:true},{dbId:3,id:13,title:"Inativo",active:false}];

test("migration é aditiva, idempotente, protegida e preserva vínculo legado",()=>{assert.match(migration,/create table if not exists public\.gallery_media_services/);assert.match(migration,/on conflict \(gallery_media_id, service_id\) do nothing/);assert.match(migration,/information_schema\.columns/);assert.match(migration,/public\.is_admin\(\)/);assert.doesNotMatch(migration,/drop table|drop column|truncate/i);});
test("mídia aceita zero, um ou vários serviços em ordem e filtra inativos",()=>{assert.deepEqual(orderedGalleryServices({},services),[]);const relations=orderedGalleryServices({serviceRelations:[{serviceId:2,displayOrder:2},{serviceId:3,displayOrder:1},{serviceId:1,displayOrder:0,isPrimary:true}]},services);assert.deepEqual(relations.map((item)=>item.service.title),["Design","Henna"]);});
test("título automático combina vários serviços e aceita fallback",()=>{const relations=orderedGalleryServices({serviceRelations:[{serviceId:1,isPrimary:true},{serviceId:2}]},services);assert.equal(resolveGalleryCopy({},relations).title,"Design + Henna");assert.equal(resolveGalleryCopy({titleSource:"combined"},relations).title,"Design + Henna");assert.equal(resolveGalleryCopy({titleSource:"custom",customTitle:"Olhar completo"},relations).title,"Design + Henna");assert.equal(resolveGalleryCopy({title:"Resultado"},[]).title,"Resultado");});
test("título de mídia com vários serviços sempre vem da combinação do catálogo",()=>{const relations=orderedGalleryServices({serviceRelations:[{serviceId:1,isPrimary:true},{serviceId:2}]},services);assert.equal(resolveGalleryCopy({titleSource:"custom",customTitle:"Texto genérico"},relations).title,"Design + Henna");});
test("descrição nunca concatena serviços",()=>{const relations=orderedGalleryServices({serviceRelations:[{serviceId:1,isPrimary:true},{serviceId:2}]},services);assert.equal(resolveGalleryCopy({},relations).description,"Descrição principal");assert.equal(resolveGalleryCopy({descriptionSource:"custom",customDescription:"Texto próprio"},relations).description,"Texto próprio");});
test("promoção é relacionada pelo id oficial do catálogo",()=>{const promotion={id:"p",service_ids:[2]};assert.equal(promotionForService(services[1],[promotion]),promotion);assert.equal(promotionForService(services[0],[promotion]),null);});
test("integração não cria preço, duração ou desconto na galeria",()=>{assert.match(page,/gallery_media_services/);assert.match(admin,/Serviços relacionados/);assert.match(admin,/Informações exibidas ao cliente/);assert.match(gallery,/calculatePromotion\(service\.priceValue,\s*promotion\)/);assert.match(gallery,/Agendar todos/);assert.match(gallery,/Agendar somente/);assert.match(gallery,/preselectedServiceIds/);assert.doesNotMatch(migration,/gallery_media[\s\S]{0,150}(price|duration|discount)/i);});
test("modal usa detalhes do catálogo e controles acessíveis",()=>{assert.match(gallery,/service\.description/);assert.match(gallery,/aria-label="Fechar detalhes"/);assert.match(gallery,/aria-label="Mídia anterior"/);assert.match(gallery,/aria-label="Próxima mídia"/);assert.match(gallery,/closeOnOverlayClick/);});
test("associação de cílios acrescenta henna somente à mídia identificada",()=>{assert.match(eyelashMigration,/3aa1d3ed-4c02-4304-979e-feeaea308717/);assert.match(eyelashMigration,/\(.*6, 0, true\)/);assert.match(eyelashMigration,/\(.*2, 1, false\)/);assert.match(eyelashMigration,/on conflict \(gallery_media_id, service_id\) do nothing/i);});
test("correção final resolve serviços por slug e limita a alteração às quatro mídias confirmadas",()=>{assert.match(correctionMigration,/slug = 'brow-lamination-sem-tintura'/);assert.match(correctionMigration,/slug = 'design-personalizado'/);assert.match(correctionMigration,/slug = 'design-com-henna'/);assert.match(correctionMigration,/slug = 'extensao-de-cilios'/);assert.match(correctionMigration,/4cca5bca-83b8-44ef-9d0a-f507330bbe6b/);assert.match(correctionMigration,/29e970d2-3f7e-4e15-ad1b-8e413fb8e906/);assert.match(correctionMigration,/edc08ab2-ebea-46dc-a7e4-dbcb995df232/);assert.match(correctionMigration,/3aa1d3ed-4c02-4304-979e-feeaea308717/);assert.match(correctionMigration,/service_id = design_com_henna_id/);assert.match(correctionMigration,/design_personalizado_id, 1, false/);assert.doesNotMatch(correctionMigration,/update public\.services|update public\.gallery_media\s/i);});
