import { useEffect, useState } from "react";
import { CalendarHeart, Plus, X } from "lucide-react";
import { Link } from "react-router-dom";
import { getAdminHolidays, saveAdminHoliday, setAdminHolidayActive } from "../../services/adminAgenda";
import { formatErrorMessage } from "../Error/errorMapper";
import Modal from "../Modal/Modal";

const labels={pending:"Decisão pendente",open_normal:"Aberto normalmente",closed:"Agenda fechada",special_hours:"Horário especial",promotion_planned:"Promoção planejada"};
const initial={name:"",holiday_date:"",scope:"nacional",city:"",state:"",admin_decision:"pending",notes:"",opening_time:"08:00",closing_time:"18:00",break_start:"12:00",break_end:"13:30"};
export default function HolidayManager({ onChanged }){
 const [items,setItems]=useState([]); const [editing,setEditing]=useState(null); const [form,setForm]=useState(initial); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 const load=()=>getAdminHolidays(new Date().toISOString().slice(0,10),`${new Date().getFullYear()+1}-12-31`).then(setItems).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 const open=(item=null)=>{setEditing(item||{});setForm(item?{...initial,...item}:initial);setError("")};
 const submit=async(e)=>{e.preventDefault();setSaving(true);setError("");try{await saveAdminHoliday({...form,appointments_reviewed:Number(editing?.appointment_count||0)===0},editing?.id);setEditing(null);await load();await onChanged?.()}catch(err){setError(formatErrorMessage(err))}finally{setSaving(false)} };
 return <section className="holiday-manager"><header><div><span>DATAS ESPECIAIS</span><h2>Feriados e funcionamento</h2><p>Defina com antecedência como o estúdio funcionará.</p></div><button type="button" onClick={()=>open()}><Plus size={17}/>Cadastrar data</button></header>{error&&<p className="agenda-error">{error}</p>}<div className="holiday-list">{items.length?items.map(item=><article key={item.id} className={!item.is_active?"is-inactive":""}><CalendarHeart/><div><strong>{item.name}</strong><span>{new Date(`${item.holiday_date}T12:00:00`).toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}</span><small>{item.scope} · {Math.max(0,Math.ceil((new Date(`${item.holiday_date}T12:00:00`)-new Date())/86400000))} dias · {labels[item.admin_decision]}</small>{Number(item.appointment_count)>0&&<em>{item.appointment_count} atendimento(s) existente(s)</em>}</div><div><button type="button" onClick={()=>open(item)}>Editar e decidir</button><button type="button" className="secondary" onClick={async()=>{await setAdminHolidayActive(item.id,!item.is_active);load()}}>{item.is_active?"Desativar":"Ativar"}</button>{item.admin_decision==="promotion_planned"&&<Link to={`/admin/promocoes?holiday=${item.id}&date=${item.holiday_date}`}>Criar promoção</Link>}</div></article>):<p>Nenhum feriado cadastrado para o período.</p>}</div>
 <Modal isOpen={editing!==null} onClose={()=>setEditing(null)} title={editing?.id?"Editar feriado":"Cadastrar feriado"} ariaLabel="Feriado" className="agenda-modal" overlayClassName="agenda-modal-backdrop"><header><button type="button" onClick={()=>setEditing(null)} aria-label="Fechar"><X/></button></header><form className="agenda-form" onSubmit={submit}><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div><label>Data<input required type="date" value={form.holiday_date} onChange={e=>setForm({...form,holiday_date:e.target.value})}/></label><label>Abrangência<select value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})}><option value="nacional">Nacional</option><option value="estadual">Estadual</option><option value="municipal">Municipal</option><option value="personalizado">Personalizado</option></select></label></div><label>Decisão<select value={form.admin_decision} onChange={e=>setForm({...form,admin_decision:e.target.value})}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{form.admin_decision==="special_hours"&&<><div><label>Abertura<input type="time" value={form.opening_time} onChange={e=>setForm({...form,opening_time:e.target.value})}/></label><label>Fechamento<input type="time" value={form.closing_time} onChange={e=>setForm({...form,closing_time:e.target.value})}/></label></div><div><label>Início da pausa<input type="time" value={form.break_start} onChange={e=>setForm({...form,break_start:e.target.value})}/></label><label>Fim da pausa<input type="time" value={form.break_end} onChange={e=>setForm({...form,break_end:e.target.value})}/></label></div></>}<label>Observações<textarea rows="3" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{Number(editing?.appointment_count)>0&&form.admin_decision==="closed"&&<p className="agenda-error">Existem atendimentos nesta data. Revise cada um antes de fechar a agenda.</p>}<button disabled={saving||Number(editing?.appointment_count)>0&&form.admin_decision==="closed"}>{saving?"Salvando...":"Salvar decisão"}</button></form></Modal>
 </section>
}
