import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, CalendarDays, CircleDollarSign, Plus, RefreshCw, Search, TrendingUp, WalletCards } from "lucide-react";
import AdminLayout from "../components/admin/AdminLayout";
import SharedModal from "../components/Modal/Modal";
import { deleteExpense, getFinancialData, recordPayment, saveExpense } from "../services/adminFinance";
import "./AdminFinance.css";
import useAccessibleDrawer from "../hooks/useAccessibleDrawer";

const money=value=>Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const dbDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const periodDates=(type,custom)=>{const now=new Date(),start=new Date(now),end=new Date(now);if(type==="today"){}else if(type==="week"){start.setDate(now.getDate()-((now.getDay()+6)%7))}else if(type==="previous"){start.setMonth(now.getMonth()-1,1);end.setDate(0)}else if(type==="year"){start.setMonth(0,1)}else if(type==="custom"&&custom.from&&custom.to)return custom;else start.setDate(1);return{from:dbDate(start),to:dbDate(end)}};
const labels={pix:"Pix",debit_card:"Cartão de débito",credit_card:"Cartão de crédito",cash:"Dinheiro",other:"Outro"};
const expenseInitial={expense_date:dbDate(new Date()),description:"",category:"materials",amount:"",payment_method:"pix",notes:"",is_recurring:false,recurrence_type:""};

export default function AdminFinance(){
 const [period,setPeriod]=useState("month"),[custom,setCustom]=useState({from:"",to:""}),[data,setData]=useState({appointments:[],transactions:[],expenses:[],services:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(1),[drawer,setDrawer]=useState(null),[modal,setModal]=useState(null),[expense,setExpense]=useState(expenseInitial),[saving,setSaving]=useState(false),[chartMode,setChartMode]=useState("daily");
 const range=useMemo(()=>periodDates(period,custom),[period,custom]);
 const load=useCallback(async()=>{if(!range.from||!range.to)return;setLoading(true);setError("");try{setData(await getFinancialData(range.from,range.to))}catch{console.error("Não foi possível carregar o financeiro.");setError("Não foi possível carregar o financeiro agora.")}finally{setLoading(false)}},[range.from,range.to]);
 useEffect(()=>{load()},[load]);
 const appointmentMap=useMemo(()=>new Map(data.appointments.map(a=>[String(a.id),a])),[data.appointments]); const serviceMap=useMemo(()=>data.services.reduce((map,s)=>{map[String(s.appointment_id)]=[...(map[String(s.appointment_id)]||[]),s];return map},{}),[data.services]);
 const received=data.transactions.filter(t=>t.payment_status==="received"&&t.transaction_type!=="refund");const gross=received.reduce((s,t)=>s+Number(t.gross_amount||t.amount),0);const fees=received.reduce((s,t)=>s+Number(t.machine_fee),0);const net=received.reduce((s,t)=>s+Number(t.net_amount),0);const reservations=received.filter(t=>t.transaction_type==="reservation").reduce((s,t)=>s+Number(t.amount),0);const expensesTotal=data.expenses.reduce((s,e)=>s+Number(e.amount),0);const result=net-expensesTotal;
 const completed=data.appointments.filter(a=>a.status==="concluido"); const pending=data.appointments.reduce((s,a)=>s+Math.max(0,Number(a.remaining_amount||0)),0); const cancelled=data.appointments.filter(a=>a.status==="cancelado").length;const noShow=data.appointments.filter(a=>["nao_compareceu","não_compareceu"].includes(a.status)).length;const ticket=completed.length?gross/completed.length:0;
 const movements=useMemo(()=>data.appointments.filter(a=>`${a.customer_name} ${a.phone} ${a.email} ${(serviceMap[String(a.id)]||[]).map(s=>s.service_name).join(" ")}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>`${b.appointment_date}${b.appointment_time}`.localeCompare(`${a.appointment_date}${a.appointment_time}`)),[data.appointments,search,serviceMap]);const paged=movements.slice((page-1)*20,page*20);
 const chart=useMemo(()=>{const groups={};received.forEach(t=>{const d=new Date(t.received_at||t.created_at);let key=dbDate(d);if(chartMode==="weekly"){const monday=new Date(d);monday.setDate(d.getDate()-((d.getDay()+6)%7));key=dbDate(monday)}if(chartMode==="monthly")key=key.slice(0,7);groups[key]=(groups[key]||0)+Number(t.net_amount)});return Object.entries(groups).sort().slice(-12)},[received,chartMode]);const maxChart=Math.max(1,...chart.map(x=>x[1]));
 const serviceRevenue=useMemo(()=>{const map={};data.services.forEach(s=>{const a=appointmentMap.get(String(s.appointment_id));if(!a)return;const appointmentReceived=received.filter(t=>String(t.appointment_id)===String(a.id)).reduce((x,t)=>x+Number(t.net_amount),0);const total=Number(a.service_price)||1;const portion=appointmentReceived*(Number(s.service_price)/total);const item=map[s.service_name]||{name:s.service_name,count:0,revenue:0};item.count+=1;item.revenue+=portion;map[s.service_name]=item});return Object.values(map).sort((a,b)=>b.revenue-a.revenue).slice(0,6)},[data.services,appointmentMap,received]);
 const openExpense=e=>{setExpense(e?{...e,amount:String(e.amount),recurrence_type:e.recurrence_type||""}:expenseInitial);setModal({type:"expense",item:e})};
 const submitExpense=async e=>{e.preventDefault();setSaving(true);try{await saveExpense(expense,modal.item?.id);setModal(null);setMessage("Despesa salva com sucesso.");await load()}catch(err){setMessage(err.message)}finally{setSaving(false)}};
 const submitPayment=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));setSaving(true);try{await recordPayment({...values,appointment_id:modal.item.id,idempotency_key:crypto.randomUUID()});setModal(null);setMessage("Pagamento registrado com sucesso.");await load()}catch(err){setMessage(err.message)}finally{setSaving(false)}};
 const exportCsv=()=>{const rows=[["Data","Cliente","Serviços","Valor","Reserva","Restante","Status"],...movements.map(a=>[a.appointment_date,a.customer_name,(serviceMap[String(a.id)]||[]).map(s=>s.service_name).join(" + "),a.service_price,a.reservation_amount,a.remaining_amount,a.status])];const blob=new Blob(["\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`financeiro-${range.from}-${range.to}.csv`;link.click();URL.revokeObjectURL(url)};
 return <AdminLayout><section className="admin-finance"><header className="finance-header"><div><span>GESTÃO</span><h1>Financeiro</h1><p>Acompanhe receitas, reservas, valores pendentes e despesas do estúdio.</p></div><div><button onClick={load}><RefreshCw size={16}/> Atualizar</button><button className="primary" onClick={()=>openExpense()}><Plus size={16}/> Nova despesa</button><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Hoje</option><option value="week">Esta semana</option><option value="month">Este mês</option><option value="previous">Mês anterior</option><option value="year">Este ano</option><option value="custom">Personalizado</option></select></div></header>{period==="custom"&&<div className="custom-period"><label>De<input type="date" value={custom.from} onChange={e=>setCustom(x=>({...x,from:e.target.value}))}/></label><label>Até<input type="date" value={custom.to} onChange={e=>setCustom(x=>({...x,to:e.target.value}))}/></label></div>}{error&&<div className="finance-state error">{error}<button onClick={load}>Tentar novamente</button></div>}{message&&<p className="finance-state">{message}</p>}
 <section className="finance-main-cards"><Metric icon={TrendingUp} label="Faturamento recebido" value={money(gross)} text="Somente valores efetivamente recebidos"/><Metric icon={WalletCards} label="Taxas de reserva recebidas" value={money(reservations)} text="Pix aprovado, sem duplicidade"/><Metric icon={CalendarDays} label="Valores restantes pendentes" value={money(pending)} text="Saldo previsto dos atendimentos"/><Metric icon={CircleDollarSign} label="Resultado do período" value={money(result)} text="Receita líquida menos despesas" tone={result>=0?"positive":"negative"}/></section>
 <section className="finance-small-cards">{[["Atendimentos concluídos",completed.length],["Pagamentos pendentes",data.appointments.filter(a=>Number(a.remaining_amount)>0).length],["Cancelamentos",cancelled],["Não comparecimentos",noShow],["Despesas registradas",data.expenses.length],["Ticket médio",money(ticket)]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</section>
 <div className="finance-charts"><section><header><div><h2>Receita no período</h2><p>Apenas valores recebidos</p></div><select value={chartMode} onChange={e=>setChartMode(e.target.value)}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select></header><div className="revenue-chart">{chart.length?chart.map(([key,value])=><div key={key}><span style={{height:`${Math.max(8,value/maxChart*150)}px`}} title={money(value)}/><small>{key.slice(5)||key}</small></div>):<p>Sem receitas recebidas no período.</p>}</div></section><section><h2>Serviços que mais geraram receita</h2><div className="service-revenue">{serviceRevenue.length?serviceRevenue.map(s=><article key={s.name}><div><strong>{s.name}</strong><small>{s.count} atendimento(s)</small></div><span>{money(s.revenue)}</span></article>):<p>Sem receita por serviço no período.</p>}</div></section></div>
 <section className="finance-movements"><header><div><h2>Movimentações</h2><p>Do registro mais recente para o mais antigo.</p></div><div><label><Search size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Cliente, telefone, e-mail ou serviço"/></label><button onClick={exportCsv}><ArrowDownToLine size={16}/> Exportar CSV</button><button onClick={()=>window.print()}>Imprimir</button></div></header>{loading?<div className="finance-state">Carregando informações financeiras...</div>:paged.length===0?<div className="finance-state">Nenhuma movimentação encontrada neste período.</div>:<div className="movement-list">{paged.map(a=>{const tx=received.filter(t=>String(t.appointment_id)===String(a.id));const got=tx.reduce((s,t)=>s+Number(t.gross_amount),0);return <article key={a.id}><div><strong>{new Date(`${a.appointment_date}T12:00`).toLocaleDateString("pt-BR")}</strong><small>{a.customer_name}</small></div><div><strong>{(serviceMap[String(a.id)]||[]).map(s=>s.service_name).join(" + ")||a.service_name}</strong><small>{a.phone}</small></div><div><small>Total</small><strong>{money(a.service_price)}</strong></div><div><small>Reserva</small><strong>{money(a.reservation_amount)}</strong></div><div><small>Recebido</small><strong>{money(got)}</strong></div><div><small>Status</small><strong>{got>=Number(a.service_price)?"Pagamento concluído":got>0?"Pagamento parcial":a.payment_status?.replaceAll("_"," ")}</strong></div><button onClick={()=>setDrawer({...a,transactions:tx,services:serviceMap[String(a.id)]||[]})}>Ver detalhes</button></article>})}</div>}<footer><span>Página {page} de {Math.max(1,Math.ceil(movements.length/20))}</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={page*20>=movements.length} onClick={()=>setPage(p=>p+1)}>Próxima</button></footer></section>
 <section className="finance-expenses"><header><h2>Despesas</h2><strong>{money(expensesTotal)}</strong></header>{data.expenses.length?data.expenses.map(e=><article key={e.id}><span>{new Date(`${e.expense_date}T12:00`).toLocaleDateString("pt-BR")}</span><div><strong>{e.description}</strong><small>{e.category}</small></div><strong>{money(e.amount)}</strong><button onClick={()=>openExpense(e)}>Editar</button><button onClick={()=>setModal({type:"delete",item:e})}>Excluir</button></article>):<p>Nenhuma despesa registrada neste período.</p>}</section>
 <section className="finance-result"><h2>Resultado do período</h2><div><span>Receitas brutas<strong>{money(gross)}</strong></span><span>Taxas da maquininha<strong>− {money(fees)}</strong></span><span>Receita líquida<strong>{money(net)}</strong></span><span>Despesas<strong>− {money(expensesTotal)}</strong></span><span className="total">Resultado líquido<strong>{money(result)}</strong></span></div></section>
 {drawer&&<FinanceDrawer item={drawer} onClose={()=>setDrawer(null)} onPayment={()=>setModal({type:"payment",item:drawer})}/>} {modal?.type==="expense"&&<ExpenseModal expense={expense} setExpense={setExpense} onClose={()=>setModal(null)} onSubmit={submitExpense} saving={saving}/>} {modal?.type==="payment"&&<PaymentModal item={modal.item} onClose={()=>setModal(null)} onSubmit={submitPayment} saving={saving}/>} {modal?.type==="delete"&&<Modal title="Excluir despesa" onClose={()=>setModal(null)}><p>A despesa será removida da apuração, mas permanecerá na auditoria.</p><footer><button onClick={()=>setModal(null)}>Voltar</button><button className="danger" onClick={async()=>{await deleteExpense(modal.item.id);setModal(null);await load()}}>Excluir despesa</button></footer></Modal>}</section></AdminLayout>;
}
function Metric({icon:Icon,label,value,text,tone=""}){return <article className={tone}><Icon/><div><span>{label}</span><strong>{value}</strong><small>{text}</small></div></article>}
function FinanceDrawer({item,onClose,onPayment}){const drawerRef=useAccessibleDrawer(Boolean(item),onClose);const total=item.transactions.reduce((s,t)=>s+Number(t.gross_amount),0),fees=item.transactions.reduce((s,t)=>s+Number(t.machine_fee),0);return <div className="finance-overlay" onClick={onClose} role="presentation"><aside ref={drawerRef} className="finance-drawer" role="dialog" aria-modal="true" aria-labelledby="finance-drawer-title" tabIndex={-1} onClick={e=>e.stopPropagation()}><header><h2 id="finance-drawer-title">Detalhes da movimentação</h2><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><h3>{item.customer_name}</h3><p>{item.phone} · {item.email}</p><dl><div><dt>Serviços</dt><dd>{item.services.map(s=>s.service_name).join(" + ")}</dd></div><div><dt>Data e horário</dt><dd>{item.appointment_date} · {item.appointment_time?.slice(0,5)}</dd></div><div><dt>Valor original</dt><dd>{money(item.original_service_price||item.service_price)}</dd></div><div><dt>Desconto</dt><dd>{money(item.promotion_discount)}</dd></div><div><dt>Valor final</dt><dd>{money(item.service_price)}</dd></div><div><dt>Reserva</dt><dd>{money(item.reservation_amount)}</dd></div><div><dt>Recebido</dt><dd>{money(total)}</dd></div><div><dt>Taxa da maquininha</dt><dd>{money(fees)}</dd></div><div><dt>Saldo</dt><dd>{money(Math.max(0,Number(item.service_price)-total))}</dd></div><div><dt>Status</dt><dd>{item.status?.replaceAll("_"," ")}</dd></div></dl><h3>Histórico financeiro</h3>{item.transactions.length?item.transactions.map(t=><article key={t.id}><strong>{money(t.gross_amount)} · {labels[t.payment_method]}</strong><small>{new Date(t.received_at).toLocaleString("pt-BR")}</small></article>):<p>Nenhum pagamento recebido.</p>}<footer><a href={`/admin/agenda?appointment=${item.id}`}>Abrir na Agenda</a><button className="primary" onClick={onPayment}>Registrar pagamento</button></footer></aside></div>}
function ExpenseModal({expense,setExpense,onClose,onSubmit,saving}){const change=e=>{const{name,value,type,checked}=e.target;setExpense(x=>({...x,[name]:type==="checkbox"?checked:value}))};return <Modal title="Nova despesa" onClose={onClose}><form className="finance-form" onSubmit={onSubmit}><label>Data*<input required type="date" name="expense_date" value={expense.expense_date} onChange={change}/></label><label>Descrição*<input required name="description" value={expense.description} onChange={change}/></label><label>Categoria*<select name="category" value={expense.category} onChange={change}><option value="materials">Materiais</option><option value="supplies">Reposição de insumos</option><option value="maintenance">Manutenção</option><option value="courses">Cursos</option><option value="marketing">Divulgação</option><option value="fees">Taxas</option><option value="other">Outras</option></select></label><label>Valor*<input required min="0.01" step="0.01" type="number" name="amount" value={expense.amount} onChange={change}/></label><label>Forma de pagamento<select name="payment_method" value={expense.payment_method} onChange={change}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Observação<textarea name="notes" rows="3" value={expense.notes||""} onChange={change}/></label><label><input type="checkbox" name="is_recurring" checked={expense.is_recurring} onChange={change}/> Despesa recorrente</label>{expense.is_recurring&&<label>Recorrência<select name="recurrence_type" value={expense.recurrence_type} onChange={change}><option value="">Selecione</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></label>}<footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Salvando...":"Salvar despesa"}</button></footer></form></Modal>}
function PaymentModal({item,onClose,onSubmit,saving}){const[method,setMethod]=useState("pix"),[amount,setAmount]=useState(String(item.remaining_amount||"")),[fee,setFee]=useState("0");return <Modal title="Registrar pagamento" onClose={onClose}><form className="finance-form" onSubmit={onSubmit}><p>Saldo atual: <strong>{money(item.remaining_amount)}</strong></p><label>Valor realmente recebido*<input required min="0.01" step="0.01" type="number" name="amount" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Forma de pagamento*<select required name="payment_method" value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{method==="credit_card"&&<label>Taxa real da maquininha<input min="0" step="0.01" type="number" name="machine_fee" value={fee} onChange={e=>setFee(e.target.value)}/></label>}<label>Data do recebimento*<input required type="datetime-local" name="received_at" defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/></label><label>Observações<textarea name="notes" rows="3"/></label><aside>Valor bruto: {money(amount)} · Taxa: {money(fee)} · Valor líquido: {money(Math.max(0,Number(amount)-Number(fee)))}</aside><footer><button type="button" onClick={onClose}>Voltar</button><button className="primary" disabled={saving}>{saving?"Salvando...":"Registrar pagamento"}</button></footer></form></Modal>}
function Modal({title,onClose,children}){return <SharedModal isOpen onClose={onClose} title={title} className="finance-modal" overlayClassName="finance-overlay">{children}</SharedModal>}
