import { useEffect, useMemo, useState } from "react";
import AdminLayout from "../components/admin/AdminLayout";
import Modal from "../components/Modal/Modal";
import { formatErrorMessage } from "../components/Error/errorMapper";
import { deleteGalleryItem, getGalleryMedia, reorderGallery, saveGalleryItem, setCentralGalleryVideo, setGalleryActive } from "../services/galleryMedia";
import { getServiceRecords, mapServiceRecord } from "../services/serviceCatalog";
import { calculatePromotion, getActivePromotions } from "../services/promotions";
import "./AdminCatalog.css";
import "./AdminGallery.css";

const empty = { media_type: "photo", title: "", category: "Resultados", alt_text: "", display_order: 0, is_active: true, is_featured: false, is_central_video: false, preferred_position: "", information_source: "catalog", title_source: "service", custom_title: "", description_source: "service", custom_description: "", service_ids: [], primary_service_id: "" };

function GalleryForm({ form, setForm, file, setFile, onClose, onSubmit, title, submitting, services, promotions }) {
  const change = ({ target }) => setForm((current) => ({ ...current, [target.name]: target.type === "checkbox" ? target.checked : target.value }));
  const preview = useMemo(() => file ? URL.createObjectURL(file) : form.public_url, [file, form.public_url]);
  useEffect(() => () => { if (file && preview) URL.revokeObjectURL(preview); }, [file, preview]);
  const toggleService = (id) => setForm((current) => { const selected=current.service_ids.includes(id); return { ...current, service_ids:selected?current.service_ids.filter((value)=>value!==id):[...current.service_ids,id], primary_service_id:selected&&current.primary_service_id===id?"":current.primary_service_id }; });
  const moveService = (id, direction) => setForm((current) => { const ids=[...current.service_ids]; const index=ids.indexOf(id); const next=index+direction; if(index<0||next<0||next>=ids.length)return current; [ids[index],ids[next]]=[ids[next],ids[index]]; return {...current,service_ids:ids}; });
  const selectedServices = form.service_ids.map((id) => services.find((service) => String(service.dbId) === id)).filter(Boolean);
  const primaryService = services.find((service) => String(service.dbId) === form.primary_service_id) || selectedServices[0];
  const automaticTitle = selectedServices.length > 1 ? selectedServices.map((service) => service.title).join(" + ") : primaryService?.title || form.title;
  const automaticDescription = primaryService?.description || "";
  return <Modal isOpen onClose={onClose} title={title} className="admin-form-modal" overlayClassName="admin-form-overlay"><form onSubmit={onSubmit}><header className="admin-form-modal__head"><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><div className="admin-form-grid">
    <label>Tipo<select name="media_type" value={form.media_type} onChange={change}><option value="photo">Foto</option><option value="video">Vídeo</option></select></label><label>Título interno*<input name="title" required value={form.title} onChange={change} /></label><label>Categoria<input name="category" value={form.category} onChange={change} /></label><label>Ordem<input name="display_order" type="number" min="0" value={form.display_order} onChange={change} /></label><label className="wide">Texto alternativo<input name="alt_text" value={form.alt_text} onChange={change} /></label>
    <fieldset className="admin-gallery-services wide"><legend>Serviços relacionados (opcional)</legend>{services.length===0?<p>Nenhum serviço disponível.</p>:services.map((service)=>{const id=String(service.dbId);const selected=form.service_ids.includes(id);return <div key={id} className="admin-gallery-service-option"><label><input type="checkbox" checked={selected} onChange={()=>toggleService(id)} />{service.title}{!service.active&&" (inativo)"}</label>{selected&&<><label className="admin-gallery-primary"><input type="radio" name="primary_service_id" checked={form.primary_service_id===id} onChange={()=>setForm((current)=>({...current,primary_service_id:id}))} />Principal</label><span className="admin-gallery-order"><button type="button" aria-label={`Subir ${service.title}`} onClick={()=>moveService(id,-1)}>↑</button><button type="button" aria-label={`Descer ${service.title}`} onClick={()=>moveService(id,1)}>↓</button></span></>}</div>;})}</fieldset>
    <fieldset className="admin-gallery-information wide"><legend>Informações exibidas ao cliente</legend><label><input type="radio" name="information_source" value="catalog" checked={form.information_source==="catalog"} onChange={change} />Usar informações automáticas do catálogo</label><label><input type="radio" name="information_source" value="custom" checked={form.information_source==="custom"} onChange={change} />Usar título e descrição personalizados</label>{form.information_source==="catalog"?<div className="admin-gallery-automatic-copy"><label>Título automático<input readOnly value={automaticTitle} /></label><label>Descrição automática<textarea readOnly rows="3" value={automaticDescription} /></label><small>Preço, duração, benefícios e promoções são sempre obtidos do catálogo.</small></div>:<div className="admin-gallery-custom-copy"><label>Título personalizado<input name="custom_title" required value={form.custom_title} onChange={change} /></label><label>Descrição personalizada<textarea name="custom_description" rows="3" value={form.custom_description} onChange={change} /></label><small>A personalização altera somente estes textos. Os dados comerciais continuam vindo do catálogo.</small></div>}</fieldset>
    {form.service_ids.length>0&&<aside className="admin-gallery-service-preview wide"><strong>Prévia do catálogo atual</strong>{form.service_ids.map((id)=>{const service=services.find((item)=>String(item.dbId)===id);if(!service)return null;const promotion=promotions.find((item)=>item.applies_to_all_services||item.service_ids?.map(String).includes(id));const value=promotion?calculatePromotion(service.priceValue,promotion).final:null;return <p key={id}>{service.title} · {service.duration} · {promotion?<><s>{service.price}</s> {value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} · Promoção</>:service.price}</p>;})}</aside>}
    <label>Arquivo{!form.id&&"*"}<input type="file" required={!form.id} accept={form.media_type==="video"?"video/mp4,video/webm":"image/jpeg,image/png,image/webp"} onChange={(event)=>setFile(event.target.files[0]||null)} />{file&&<small>{file.name} · {(file.size/1024/1024).toFixed(2)} MB</small>}</label>{preview&&(form.media_type==="video"?<video className="admin-media-preview" src={preview} muted controls />:<img className="admin-media-preview" src={preview} alt="Pré-visualização" />)}<div className="admin-checks wide"><label><input name="is_active" type="checkbox" checked={form.is_active} onChange={change} /> Ativo</label><label><input name="is_featured" type="checkbox" checked={form.is_featured} onChange={change} /> Destaque</label>{form.media_type==="video"&&<label><input name="is_central_video" type="checkbox" checked={form.is_central_video} onChange={change} /> Vídeo central</label>}</div>{submitting&&<p className="admin-upload-progress wide">Enviando arquivo e salvando dados...</p>}
  </div><div className="admin-form-actions"><button type="button" className="admin-action" disabled={submitting} onClick={onClose}>Cancelar</button><button className="admin-primary" disabled={submitting}>{submitting?"Enviando...":"Salvar mídia"}</button></div></form></Modal>;
}

export default function AdminGallery() {
  const [items,setItems]=useState([]);const [services,setServices]=useState([]);const [promotions,setPromotions]=useState([]);const [editing,setEditing]=useState(null);const [modal,setModal]=useState(false);const [deleting,setDeleting]=useState(null);const [form,setForm]=useState(empty);const [file,setFile]=useState(null);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);
  const load=()=>{setLoading(true);return getGalleryMedia({admin:true}).then(setItems).catch(()=>setMessage("Não foi possível carregar a galeria.")).finally(()=>setLoading(false));};
  useEffect(()=>{void load();Promise.all([getServiceRecords({admin:true}),getActivePromotions("services")]).then(([records,active])=>{setServices(records.map((record)=>mapServiceRecord(record)));setPromotions(active);}).catch(()=>setMessage("Não foi possível carregar o catálogo para as associações."));},[]);
  const open=(item)=>{const relations=(item?.gallery_media_services||[]).slice().sort((a,b)=>a.display_order-b.display_order);const custom=item?.title_source==="custom"||item?.description_source==="custom";setEditing(item||null);setForm(item?{...empty,...item,information_source:custom?"custom":"catalog",service_ids:relations.map((relation)=>String(relation.service_id)),primary_service_id:String(relations.find((relation)=>relation.is_primary)?.service_id||"")}:{...empty});setFile(null);setModal(true);};
  const submit=async(event)=>{event.preventDefault();if(submitting)return;setSubmitting(true);try{await saveGalleryItem(form,file,editing?.id,editing?.storage_path);setModal(false);setMessage("Mídia salva com sucesso.");await load();}catch(error){setMessage(formatErrorMessage(error)||"Não foi possível salvar a mídia.");}finally{setSubmitting(false);}};
  const toggle=async(item)=>{try{await setGalleryActive(item.id,!item.is_active);await load();}catch(error){setMessage(formatErrorMessage(error)||"Não foi possível atualizar o estado da mídia.");}};
  const remove=async()=>{const item=deleting;if(!item)return;setSubmitting(true);try{await deleteGalleryItem(item);setDeleting(null);setMessage("Mídia excluída com sucesso.");await load();}catch(error){setMessage(formatErrorMessage(error)||"Não foi possível remover a mídia.");}finally{setSubmitting(false);}};
  const move=async(index,direction)=>{const next=index+direction;if(next<0||next>=items.length)return;const updated=[...items];[updated[index],updated[next]]=[updated[next],updated[index]];setItems(updated);try{await reorderGallery(updated);}catch(error){setMessage(formatErrorMessage(error)||"Não foi possível reordenar a galeria.");await load();}};
  const centralize=async(item)=>{try{await setCentralGalleryVideo(item.id);setMessage("Vídeo central atualizado com sucesso.");await load();}catch{setMessage("Não foi possível definir o vídeo central.");}};
  const photos=items.filter((item)=>item.media_type==="photo").length;const active=items.filter((item)=>item.is_active).length;
  return <AdminLayout><section className="admin-catalog"><header className="admin-catalog__header"><div><span>CONTEÚDO</span><h1>Gestão da Galeria</h1><p>Atualize as fotos e vídeos exibidos no site.</p></div><button className="admin-primary" onClick={()=>open(null)}>Adicionar mídia</button></header><div className="admin-catalog__metrics"><article><span>Fotos</span><strong>{photos}</strong></article><article><span>Vídeos</span><strong>{items.length-photos}</strong></article><article><span>Ativas</span><strong>{active}</strong></article></div>{message&&<div className={`admin-message ${message.includes("sucesso")?"":"error"}`}><span>{message}</span></div>}{loading?<p className="admin-loading">Carregando galeria...</p>:items.length===0?<p className="admin-empty-state">Nenhuma mídia cadastrada.</p>:<div className="admin-gallery-grid">{items.map((item,index)=><article className="admin-gallery-card" key={item.id}>{item.media_type==="video"?<video src={item.public_url} muted controls />:<img src={item.public_url} alt={item.alt_text} />}<div className="admin-gallery-card__body"><h2>{item.title}</h2><div className="admin-gallery-card__meta"><span>{item.media_type==="video"?"Vídeo":"Foto"} · {item.category}</span><span>{item.is_active?"Ativo":"Pausado"}</span></div><small>{item.gallery_media_services?.length||0} serviço(s) · Posição {item.display_order}</small><div className="admin-row-actions"><button className="admin-action" onClick={()=>open(item)}>Editar/Substituir</button><button className="admin-action" onClick={()=>toggle(item)}>{item.is_active?"Pausar":"Ativar"}</button><button className="admin-action" onClick={()=>move(index,-1)} aria-label="Mover para frente">←</button><button className="admin-action" onClick={()=>move(index,1)} aria-label="Mover para trás">→</button>{item.media_type==="video"&&!item.is_central_video&&<button className="admin-action" onClick={()=>centralize(item)}>Definir central</button>}<a className="admin-action" href="/galeria">Visualizar</a><button className="admin-action danger" onClick={()=>setDeleting(item)}>Excluir</button></div></div></article>)}</div>}{modal&&<GalleryForm form={form} setForm={setForm} file={file} setFile={setFile} onClose={()=>setModal(false)} onSubmit={submit} submitting={submitting} services={services} promotions={promotions} title={editing?"Editar mídia":"Adicionar mídia"} />}<Modal isOpen={Boolean(deleting)} onClose={()=>setDeleting(null)} title="Excluir mídia" describedBy="delete-media-description" className="admin-confirm-modal"><p id="delete-media-description">Tem certeza de que deseja excluir {deleting?.title}?</p><div className="admin-form-actions"><button type="button" disabled={submitting} onClick={()=>setDeleting(null)}>Voltar</button><button type="button" className="danger" disabled={submitting} onClick={remove}>{submitting?"Excluindo...":"Confirmar exclusão"}</button></div></Modal></section></AdminLayout>;
}
