import { lazy } from "react";
import { Navigate, Route, Routes } from "react-router-dom";
import AdminRoute from "./components/auth/AdminRoute";
import ProtectedRoute from "./components/auth/ProtectedRoute";
import RouteLoadingBoundary from "./components/RouteLoadingBoundary/RouteLoadingBoundary";

const Home=lazy(()=>import("./pages/Home")); const Contact=lazy(()=>import("./pages/Contact")); const Gallery=lazy(()=>import("./pages/Gallery")); const MyStory=lazy(()=>import("./pages/MyStory"));
const Auth=lazy(()=>import("./pages/Auth")); const RecoverPassword=lazy(()=>import("./pages/RecoverPassword")); const NewPassword=lazy(()=>import("./pages/NewPassword")); const Services=lazy(()=>import("./pages/Services")); const ServiceDetails=lazy(()=>import("./pages/ServiceDetails")); const Booking=lazy(()=>import("./pages/Booking")); const CancellationFlow=lazy(()=>import("./pages/CancellationFlow"));
const CustomerSpace=lazy(()=>import("./pages/CustomerSpace")); const CustomerAppointments=lazy(()=>import("./pages/CustomerAppointments")); const CustomerSettings=lazy(()=>import("./pages/CustomerSettings"));
const CustomerAppointmentDetails=lazy(()=>import("./pages/CustomerAppointmentDetails")); const NotFound=lazy(()=>import("./pages/NotFound"));
const AdminDashboard=lazy(()=>import("./pages/AdminDashboard")); const AdminGallery=lazy(()=>import("./pages/AdminGallery")); const AdminAgenda=lazy(()=>import("./pages/AdminAgenda")); const AdminRequests=lazy(()=>import("./pages/AdminRequests")); const AdminCustomers=lazy(()=>import("./pages/AdminCustomers")); const AdminServices=lazy(()=>import("./pages/AdminServices")); const AdminPromotions=lazy(()=>import("./pages/AdminPromotions")); const AdminFinance=lazy(()=>import("./pages/AdminFinance")); const AdminSettings=lazy(()=>import("./pages/AdminSettings")); const AdminAbout=lazy(()=>import("./pages/AdminAbout"));

const protectedCustomer=(page)=><ProtectedRoute>{page}</ProtectedRoute>; const protectedAdmin=(page)=><AdminRoute>{page}</AdminRoute>;
export default function App(){return <RouteLoadingBoundary><Routes>
  <Route path="/" element={<Home/>}/><Route path="/contato" element={<Contact/>}/><Route path="/galeria" element={<Gallery/>}/><Route path="/minha-historia" element={<MyStory/>}/><Route path="/entrar" element={<Auth mode="signin"/>}/><Route path="/cadastro" element={<Auth mode="signup"/>}/><Route path="/recuperar-senha" element={<RecoverPassword/>}/><Route path="/nova-senha" element={<NewPassword/>}/><Route path="/servicos" element={<Services/>}/><Route path="/servicos/:slug" element={<ServiceDetails/>}/><Route path="/agendamento/:id" element={<Booking/>}/><Route path="/cancelar-agendamento/:id" element={<CancellationFlow/>}/>
  <Route path="/minha-conta" element={protectedCustomer(<CustomerSpace/>)}/><Route path="/minha-conta/agendamentos" element={protectedCustomer(<CustomerAppointments/>)}/><Route path="/minha-conta/agendamentos/:id" element={protectedCustomer(<CustomerAppointmentDetails/>)}/><Route path="/minha-conta/configuracoes" element={protectedCustomer(<CustomerSettings/>)}/>
  <Route path="/admin" element={protectedAdmin(<AdminDashboard/>)}/><Route path="/admin/sobre" element={protectedAdmin(<AdminAbout/>)}/><Route path="/admin/pagamentos" element={protectedAdmin(<Navigate to="/admin/solicitacoes?tab=pagamentos" replace/>)}/><Route path="/admin/financeiro" element={protectedAdmin(<AdminFinance/>)}/><Route path="/admin/servicos" element={protectedAdmin(<AdminServices/>)}/><Route path="/admin/galeria" element={protectedAdmin(<AdminGallery/>)}/><Route path="/admin/agenda" element={protectedAdmin(<AdminAgenda/>)}/><Route path="/admin/solicitacoes" element={protectedAdmin(<AdminRequests/>)}/><Route path="/admin/clientes" element={protectedAdmin(<AdminCustomers/>)}/><Route path="/admin/promocoes" element={protectedAdmin(<AdminPromotions/>)}/><Route path="/admin/configuracoes" element={protectedAdmin(<AdminSettings/>)}/>
  <Route path="*" element={<NotFound/>}/>
</Routes></RouteLoadingBoundary>}
