create table if not exists public.customer_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  phone text,
  promotions_authorized boolean not null default false,
  is_active boolean not null default true,
  deactivation_reason text,
  deactivated_at timestamptz,
  deactivated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_notes (
  id bigint generated by default as identity primary key,
  identity_key text not null,
  customer_id uuid references auth.users(id) on delete set null,
  guest_email text,
  guest_phone text,
  note text not null check (length(trim(note)) > 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_active boolean not null default true
);
create index if not exists customer_notes_identity_idx on public.customer_notes(identity_key, created_at desc);

alter table public.customer_accounts enable row level security;
alter table public.customer_notes enable row level security;
create policy "Customers view own account" on public.customer_accounts for select to authenticated using (user_id=auth.uid());
create policy "Admins manage customer accounts" on public.customer_accounts for all to authenticated using ((auth.jwt()->'app_metadata'->>'role')='admin') with check ((auth.jwt()->'app_metadata'->>'role')='admin');
create policy "Admins manage customer notes" on public.customer_notes for all to authenticated using ((auth.jwt()->'app_metadata'->>'role')='admin') with check ((auth.jwt()->'app_metadata'->>'role')='admin');

create or replace function public.sync_customer_account() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.customer_accounts(user_id,email,full_name,phone,created_at,updated_at)
  values(new.id,lower(trim(new.email)),coalesce(new.raw_user_meta_data->>'name',new.raw_user_meta_data->>'full_name'),new.raw_user_meta_data->>'phone',new.created_at,now())
  on conflict(user_id) do update set email=excluded.email,full_name=coalesce(excluded.full_name,customer_accounts.full_name),phone=coalesce(excluded.phone,customer_accounts.phone),updated_at=now();
  return new;
end $$;
drop trigger if exists sync_customer_account_trigger on auth.users;
create trigger sync_customer_account_trigger after insert or update of email,raw_user_meta_data on auth.users for each row execute function public.sync_customer_account();
insert into public.customer_accounts(user_id,email,full_name,phone,created_at)
select id,lower(trim(email)),coalesce(raw_user_meta_data->>'name',raw_user_meta_data->>'full_name'),raw_user_meta_data->>'phone',created_at from auth.users where email is not null
on conflict(user_id) do nothing;

create or replace function public.link_customer_history() returns integer language plpgsql security definer set search_path=public as $$
declare linked integer; session_email text;
begin
  if auth.uid() is null then raise exception 'Autenticação necessária'; end if;
  session_email:=lower(trim(auth.jwt()->>'email'));
  if session_email is null or session_email='' then raise exception 'E-mail autenticado não encontrado'; end if;
  update public.appointments set user_id=auth.uid() where user_id is null and lower(trim(email))=session_email;
  get diagnostics linked=row_count;
  insert into public.request_activity(request_type,request_id,action,description,performed_by)
  values('cliente',auth.uid()::text,'historico_vinculado',concat(linked,' agendamento(s) antigo(s) vinculado(s).'),auth.uid());
  return linked;
end $$;
revoke all on function public.link_customer_history() from public;
grant execute on function public.link_customer_history() to authenticated;

create or replace function public.admin_add_customer_note(target_identity text,note_text text,target_user uuid default null,target_email text default null,target_phone text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare new_id bigint;
begin
 if coalesce(auth.jwt()->'app_metadata'->>'role','')<>'admin' then raise exception 'Acesso administrativo necessário'; end if;
 if nullif(trim(note_text),'') is null then raise exception 'Informe a observação'; end if;
 insert into public.customer_notes(identity_key,customer_id,guest_email,guest_phone,note,created_by) values(target_identity,target_user,lower(trim(target_email)),regexp_replace(target_phone,'\D','','g'),trim(note_text),auth.uid()) returning id into new_id;
 return new_id;
end $$;

create or replace function public.admin_set_customer_active(target_user uuid,active_value boolean,reason_text text default null)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if coalesce(auth.jwt()->'app_metadata'->>'role','')<>'admin' then raise exception 'Acesso administrativo necessário'; end if;
 update public.customer_accounts set is_active=active_value,deactivation_reason=case when active_value then null else reason_text end,deactivated_at=case when active_value then null else now() end,deactivated_by=case when active_value then null else auth.uid() end,updated_at=now() where user_id=target_user;
 if not found then raise exception 'Conta cadastrada não encontrada'; end if;
 return true;
end $$;

create or replace function public.get_admin_customers(page_number integer default 1,page_size integer default 20,search_text text default null,filter_name text default 'all',sort_name text default 'recent')
returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb;
begin
 if coalesce(auth.jwt()->'app_metadata'->>'role','')<>'admin' then raise exception 'Acesso administrativo necessário'; end if;
 with appointment_data as (
   select a.*,case when a.user_id is not null then 'u:'||a.user_id::text when nullif(lower(trim(a.email)),'') is not null then 'e:'||lower(trim(a.email)) else 'p:'||regexp_replace(coalesce(a.phone,''),'\D','','g') end identity_key
   from public.appointments a
 ), appointment_enriched as (
   select a.*,coalesce((select jsonb_agg(to_jsonb(s)) from public.appointment_services s where s.appointment_id=a.id),'[]'::jsonb) services
   from appointment_data a
 ), identities as (
   select 'u:'||c.user_id::text identity_key,c.user_id,lower(trim(c.email)) email,regexp_replace(coalesce(c.phone,''),'\D','','g') phone,c.full_name,c.created_at,c.updated_at,c.is_active,c.promotions_authorized from public.customer_accounts c
   union
   select distinct on(identity_key) identity_key,a.user_id,lower(trim(a.email)),regexp_replace(coalesce(a.phone,''),'\D','','g'),a.customer_name,a.created_at,a.created_at,true,false from appointment_data a
   where not exists(select 1 from public.customer_accounts c where c.user_id=a.user_id) order by identity_key,created_at
 ), consolidated as (
   select i.*,
    coalesce((select min(a.created_at) from appointment_data a where a.identity_key=i.identity_key),i.created_at) first_contact,
    (select max(a.appointment_date) from appointment_data a where a.identity_key=i.identity_key and a.status='concluido') last_completed,
    (select min(a.appointment_date) from appointment_data a where a.identity_key=i.identity_key and a.status not in('cancelado','concluido') and a.appointment_date>=current_date) next_appointment,
    (select count(*) from appointment_data a where a.identity_key=i.identity_key) total_appointments,
    (select count(*) from appointment_data a where a.identity_key=i.identity_key and a.status='concluido') completed_count,
    (select count(*) from appointment_data a where a.identity_key=i.identity_key and a.status='cancelado') cancellation_count,
    (select count(*) from appointment_data a where a.identity_key=i.identity_key and a.status in('nao_compareceu','ausente')) no_show_count,
    (select coalesce(sum(a.service_price),0) from appointment_data a where a.identity_key=i.identity_key and a.status='concluido') total_spent,
    (select coalesce(sum(a.reservation_amount),0) from appointment_data a where a.identity_key=i.identity_key and a.reservation_paid) reservation_spent,
    (select max(a.created_at) from appointment_data a where a.identity_key=i.identity_key) last_activity
   from identities i
 ), filtered as (
  select * from consolidated c where
   (nullif(trim(search_text),'') is null or c.full_name ilike '%'||trim(search_text)||'%' or c.email ilike '%'||trim(search_text)||'%' or c.phone like '%'||regexp_replace(search_text,'\D','','g')||'%' or exists(select 1 from appointment_data a join public.appointment_services s on s.appointment_id=a.id where a.identity_key=c.identity_key and s.service_name ilike '%'||trim(search_text)||'%'))
   and case filter_name when 'registered' then c.user_id is not null when 'guest' then c.user_id is null when 'recurring' then c.completed_count>=2 when 'new' then date_trunc('month',c.first_contact)=date_trunc('month',current_date) when 'inactive' then c.last_completed<current_date-90 and c.next_appointment is null when 'upcoming' then c.next_appointment is not null when 'cancelled' then c.cancellation_count>0 when 'no_show' then c.no_show_count>0 when 'active' then c.is_active and (c.next_appointment is not null or c.last_completed>=current_date-90) when 'disabled' then not c.is_active else true end
 ), paged as (
  select * from filtered order by
   case when sort_name='name' then lower(full_name) end asc,
   case when sort_name='appointments' then completed_count end desc,
   case when sort_name='spent' then total_spent end desc,
   case when sort_name='last_service' then last_completed end desc nulls last,
   case when sort_name='recent' then first_contact end desc,
   first_contact desc limit greatest(1,page_size) offset (greatest(1,page_number)-1)*greatest(1,page_size)
 )
 select jsonb_build_object('total',(select count(*) from filtered),'metrics',jsonb_build_object(
   'total',(select count(*) from consolidated),
   'new_this_month',(select count(*) from consolidated where date_trunc('month',first_contact)=date_trunc('month',current_date)),
   'new_previous_month',(select count(*) from consolidated where date_trunc('month',first_contact)=date_trunc('month',current_date-interval '1 month')),
   'recurring',(select count(*) from consolidated where completed_count>=2),
   'without_recent',(select count(*) from consolidated where last_completed<current_date-90 and next_appointment is null)
  ),'clients',coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object(
   'appointments',coalesce((select jsonb_agg(to_jsonb(a) order by a.appointment_date desc,a.appointment_time desc) from appointment_enriched a where a.identity_key=p.identity_key),'[]'::jsonb),
   'notes',coalesce((select jsonb_agg(to_jsonb(n) order by n.created_at desc) from public.customer_notes n where n.identity_key=p.identity_key and n.is_active),'[]'::jsonb)
  )),'[]'::jsonb)) into result from paged p;
 return result;
end $$;

revoke all on function public.admin_add_customer_note(text,text,uuid,text,text) from public;
revoke all on function public.admin_set_customer_active(uuid,boolean,text) from public;
revoke all on function public.get_admin_customers(integer,integer,text,text,text) from public;
grant execute on function public.admin_add_customer_note(text,text,uuid,text,text) to authenticated;
grant execute on function public.admin_set_customer_active(uuid,boolean,text) to authenticated;
grant execute on function public.get_admin_customers(integer,integer,text,text,text) to authenticated;
