create table if not exists public.studio_settings (
 id text primary key default 'main', public_data jsonb not null default '{}'::jsonb,
 private_data jsonb not null default '{}'::jsonb, updated_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.schedule_settings (
 id text primary key default 'default', settings jsonb not null default '{}'::jsonb,
 updated_by uuid references auth.users(id) on delete set null, updated_at timestamptz not null default now()
);
create table if not exists public.notification_preferences (
 id text primary key, panel_enabled boolean not null default true, email_enabled boolean not null default false,
 priority text not null default 'normal' check(priority in('low','normal','high')), updated_by uuid references auth.users(id) on delete set null, updated_at timestamptz not null default now()
);
create table if not exists public.email_templates (
 id text primary key, subject text not null, title text not null, body text not null, signature text not null default 'Thaís Santos Beauty Studio',
 required_variables text[] not null default '{}', updated_by uuid references auth.users(id) on delete set null, updated_at timestamptz not null default now()
);
create table if not exists public.policy_versions (
 id uuid primary key default gen_random_uuid(), policy_type text not null, version integer not null,
 content text not null, is_active boolean not null default true, created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(), unique(policy_type,version)
);
create unique index if not exists one_active_policy_per_type on public.policy_versions(policy_type) where is_active;
create table if not exists public.system_settings_activity (
 id bigint generated by default as identity primary key, section text not null, action text not null,
 previous_value jsonb, new_value jsonb, performed_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now()
);
create table if not exists public.admin_role_activity (
 id bigint generated by default as identity primary key, target_user uuid not null, action text not null,
 performed_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now()
);

alter table public.studio_settings enable row level security; alter table public.schedule_settings enable row level security;
alter table public.notification_preferences enable row level security; alter table public.email_templates enable row level security;
alter table public.policy_versions enable row level security; alter table public.system_settings_activity enable row level security;
alter table public.admin_role_activity enable row level security;
create policy "Admins manage studio settings" on public.studio_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Admins manage schedule settings" on public.schedule_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Admins manage notification preferences" on public.notification_preferences for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Admins manage email templates" on public.email_templates for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Admins manage policy versions" on public.policy_versions for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "Admins read settings activity" on public.system_settings_activity for select to authenticated using(public.is_admin());
create policy "Admins read role activity" on public.admin_role_activity for select to authenticated using(public.is_admin());

insert into public.studio_settings(id,public_data,private_data) values('main',
 jsonb_build_object('studio_name','Thaís Santos Beauty Studio','professional_name','Thaís Santos','tagline','Beleza com cuidado e naturalidade','description','','contact_email','','phone','','instagram','https://www.instagram.com/thaissantos.studio','neighborhood','São João Clímaco','city','São Paulo','state','SP','map_link','','logo_path','','profile_image_path','','payment_methods',jsonb_build_object('pix',true,'debit_card',true,'credit_card',true,'cash',true),'credit_card_notice','Pagamentos realizados no cartão de crédito estarão sujeitos à taxa da maquininha.','site',jsonb_build_object('home_title','Um momento especial começa aqui','home_subtitle','','primary_button','Agendar agora','gallery_button','Ver galeria','instagram_call','Inspire-se com ainda mais resultados.','contact_text','','menu',jsonb_build_object('home','Home','services','Serviços','story','Minha História','gallery','Galeria','contact','Contato'))),
 jsonb_build_object('full_address','','pix_configured',true,'pix_recipient_name','','pix_recipient_city','São Paulo','proof_deadline_minutes',30,'payment_message','Realize o pagamento da reserva via Pix.','payment_sent_message','Recebemos seu comprovante.','initial_status','aguardando_pagamento','allow_pix_copy_paste',true,'allow_qr_code',true,'require_proof',true,'integration_status',jsonb_build_object('resend',false,'sender',false,'admin_email',true,'site_url',true))) on conflict(id) do nothing;

insert into public.schedule_settings(id,settings) values('default',jsonb_build_object(
 'slot_interval',30,'minimum_duration',10,'future_months',3,'release_reminders',jsonb_build_array(20,25,31),
 'days',jsonb_build_object('1',jsonb_build_object('active',true,'open','08:00','break_start','12:00','break_end','13:30','close','18:00'),'2',jsonb_build_object('active',true,'open','08:00','break_start','12:00','break_end','13:30','close','18:00'),'3',jsonb_build_object('active',true,'open','08:00','break_start','12:00','break_end','13:30','close','18:00'),'4',jsonb_build_object('active',false),'5',jsonb_build_object('active',true,'open','08:00','break_start','12:00','break_end','13:30','close','18:00'),'6',jsonb_build_object('active',true,'open','08:00','break_start','','break_end','','close','15:00'),'0',jsonb_build_object('active',false)))) on conflict(id) do nothing;

insert into public.policy_versions(policy_type,version,content) values
('reservation',1,'Estou ciente de que a taxa de reserva garante o horário escolhido e que, em caso de não comparecimento ou cancelamento, o valor pago não será reembolsado, conforme a política de agendamento do estúdio.'),
('cancellation',1,'O cancelamento é permitido antes do início do atendimento. O horário será liberado imediatamente e a taxa de reserva não é reembolsável.'),
('image_authorization',1,'Você autoriza a utilização de fotos ou vídeos do resultado do procedimento para divulgação?'),
('address_notice',1,'O endereço completo é enviado após a confirmação do agendamento.') on conflict do nothing;

insert into public.notification_preferences(id) values ('new_appointment'),('payment_proof'),('payment_refused'),('cancellation'),('booking_request'),('reschedule'),('schedule_release'),('promotion_ending'),('new_customer') on conflict do nothing;
insert into public.email_templates(id,subject,title,body,required_variables) values
('signup','Bem-vinda ao BeautyFlow','Cadastro concluído','Olá {{customer_name}}, seu espaço está pronto.','{customer_name}'),
('payment_review','Pagamento em análise','Recebemos seu comprovante','Olá {{customer_name}}, estamos analisando seu pagamento.','{customer_name}'),
('payment_confirmed','Pagamento confirmado','Agendamento confirmado','Seu atendimento de {{service_name}} será em {{appointment_date}} às {{appointment_time}}.','{customer_name,service_name,appointment_date,appointment_time}'),
('payment_refused','Comprovante não aprovado','Precisamos de um novo comprovante','Olá {{customer_name}}, revise as orientações enviadas.','{customer_name}'),
('appointment_confirmed','Agendamento confirmado','Está tudo certo','Olá {{customer_name}}, esperamos você em {{appointment_date}} às {{appointment_time}}.','{customer_name,appointment_date,appointment_time}'),
('cancellation','Agendamento cancelado','Cancelamento recebido','O atendimento de {{service_name}} foi cancelado.','{customer_name,service_name}'),
('reminder_24h','Seu atendimento é amanhã','Lembrete do seu atendimento','Olá {{customer_name}}, esperamos você amanhã às {{appointment_time}}.','{customer_name,appointment_time}'),
('promotion','Uma novidade para você','Oferta especial','Olá {{customer_name}}, confira nossa novidade.','{customer_name}') on conflict do nothing;

create or replace function public.get_public_settings() returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('studio',coalesce((select public_data from public.studio_settings where id='main'),'{}'::jsonb),'schedule',coalesce((select settings from public.schedule_settings where id='default'),'{}'::jsonb),'policies',coalesce((select jsonb_object_agg(policy_type,jsonb_build_object('id',id,'version',version,'content',content)) from public.policy_versions where is_active),'{}'::jsonb)) $$;

create or replace function public.admin_get_settings() returns jsonb language plpgsql security definer set search_path=public as $$ begin
 if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if;
 return jsonb_build_object('studio',(select to_jsonb(s) from public.studio_settings s where id='main'),'schedule',(select to_jsonb(s) from public.schedule_settings s where id='default'),'policies',(select coalesce(jsonb_agg(to_jsonb(p) order by p.policy_type,p.version desc),'[]') from public.policy_versions p),'notifications',(select coalesce(jsonb_agg(to_jsonb(n) order by n.id),'[]') from public.notification_preferences n),'templates',(select coalesce(jsonb_agg(to_jsonb(e) order by e.id),'[]') from public.email_templates e),'admins',(select coalesce(jsonb_agg(jsonb_build_object('id',u.id,'name',coalesce(u.raw_user_meta_data->>'name',split_part(u.email,'@',1)),'email',u.email,'created_at',u.created_at,'last_sign_in_at',u.last_sign_in_at,'role',u.raw_app_meta_data->>'role')),'[]') from auth.users u where u.raw_app_meta_data->>'role'='admin'));
end $$;

create or replace function public.admin_save_settings(section text,payload jsonb) returns void language plpgsql security definer set search_path=public as $$ declare old jsonb; begin
 if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if;
 if section='profile' or section='payments' or section='site' then select case when section='profile' or section='site' then public_data else private_data end into old from public.studio_settings where id='main'; update public.studio_settings set public_data=case when section in('profile','site') then public_data||payload else public_data end,private_data=case when section='payments' then private_data||payload else private_data end,updated_by=auth.uid(),updated_at=now() where id='main';
 elsif section='schedule' then select settings into old from public.schedule_settings where id='default'; update public.schedule_settings set settings=payload,updated_by=auth.uid(),updated_at=now() where id='default';
 else raise exception 'Seção inválida'; end if;
 insert into public.system_settings_activity(section,action,previous_value,new_value,performed_by) values(section,'updated',case when section='payments' then jsonb_build_object('masked',true) else old end,case when section='payments' then jsonb_build_object('masked',true) else payload end,auth.uid());
end $$;

create or replace function public.admin_save_policy(target_type text,target_content text) returns uuid language plpgsql security definer set search_path=public as $$ declare result uuid; next_version integer; begin
 if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if; if trim(target_content)='' then raise exception 'O texto da política é obrigatório'; end if;
 select coalesce(max(version),0)+1 into next_version from public.policy_versions where policy_type=target_type; update public.policy_versions set is_active=false where policy_type=target_type and is_active;
 insert into public.policy_versions(policy_type,version,content,created_by) values(target_type,next_version,target_content,auth.uid()) returning id into result;
 insert into public.system_settings_activity(section,action,new_value,performed_by) values('policies','version_created',jsonb_build_object('type',target_type,'version',next_version),auth.uid()); return result;
end $$;

create or replace function public.admin_save_notifications(payload jsonb) returns void language plpgsql security definer set search_path=public as $$ declare item jsonb; begin if not public.is_admin() then raise exception 'Acesso negado'; end if; for item in select * from jsonb_array_elements(payload) loop update public.notification_preferences set panel_enabled=(item->>'panel_enabled')::boolean,email_enabled=(item->>'email_enabled')::boolean,priority=item->>'priority',updated_by=auth.uid(),updated_at=now() where id=item->>'id'; end loop; insert into public.system_settings_activity(section,action,new_value,performed_by) values('notifications','updated',payload,auth.uid()); end $$;
create or replace function public.admin_save_email_template(payload jsonb) returns void language plpgsql security definer set search_path=public as $$ declare required text; begin if not public.is_admin() then raise exception 'Acesso negado'; end if; for required in select unnest(required_variables) from public.email_templates where id=payload->>'id' loop if position(required in payload->>'body')=0 then raise exception 'A variável obrigatória % não pode ser removida',required; end if; end loop; update public.email_templates set subject=payload->>'subject',title=payload->>'title',body=payload->>'body',signature=payload->>'signature',updated_by=auth.uid(),updated_at=now() where id=payload->>'id'; insert into public.system_settings_activity(section,action,new_value,performed_by) values('emails','template_updated',jsonb_build_object('id',payload->>'id'),auth.uid()); end $$;

create or replace function public.admin_set_role(target_email text,make_admin boolean) returns void language plpgsql security definer set search_path=public as $$ declare target auth.users%rowtype; admin_count integer; begin
 if not public.is_admin() then raise exception 'Acesso negado'; end if; select * into target from auth.users where lower(email)=lower(trim(target_email)); if not found then raise exception 'Conta não encontrada'; end if;
 if not make_admin then select count(*) into admin_count from auth.users where raw_app_meta_data->>'role'='admin'; if admin_count<=1 then raise exception 'O sistema precisa manter ao menos um administrador'; end if; if target.id=auth.uid() and admin_count<=1 then raise exception 'O último administrador não pode remover a própria permissão'; end if; end if;
 update auth.users set raw_app_meta_data=case when make_admin then coalesce(raw_app_meta_data,'{}')||'{"role":"admin"}'::jsonb else coalesce(raw_app_meta_data,'{}')-'role' end where id=target.id;
 insert into public.admin_role_activity(target_user,action,performed_by) values(target.id,case when make_admin then 'promoted' else 'removed' end,auth.uid());
end $$;

grant execute on function public.get_public_settings() to anon,authenticated; grant execute on function public.admin_get_settings() to authenticated;
grant execute on function public.admin_save_settings(text,jsonb) to authenticated; grant execute on function public.admin_save_policy(text,text) to authenticated;
grant execute on function public.admin_save_notifications(jsonb) to authenticated; grant execute on function public.admin_save_email_template(jsonb) to authenticated;
grant execute on function public.admin_set_role(text,boolean) to authenticated;
