alter table public.appointments
  add column if not exists reservation_policy_accepted boolean not null default false,
  add column if not exists payment_reviewed_at timestamptz,
  add column if not exists payment_reviewed_by uuid references auth.users(id),
  add column if not exists payment_rejection_reason text,
  add column if not exists payment_rejection_notes text;

alter table public.booking_requests
  add column if not exists reviewed_by uuid references auth.users(id),
  add column if not exists proposed_date date,
  add column if not exists proposed_time text,
  add column if not exists admin_message text,
  add column if not exists rejection_reason text;

create table if not exists public.reschedule_requests (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  requested_date date not null,
  requested_time text not null,
  reason text,
  status text not null default 'pendente',
  proposed_date date,
  proposed_time text,
  admin_message text,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.request_activity (
  id bigint generated by default as identity primary key,
  request_type text not null,
  request_id text not null,
  action text not null,
  description text,
  performed_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.reschedule_requests enable row level security;
alter table public.request_activity enable row level security;

drop policy if exists "Admins manage reschedule requests" on public.reschedule_requests;
create policy "Admins manage reschedule requests" on public.reschedule_requests
for all to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins view request activity" on public.request_activity;
create policy "Admins view request activity" on public.request_activity
for select to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create or replace function public.admin_review_payment(
  target_appointment_id uuid,
  approved boolean,
  rejection_reason text default null,
  rejection_notes text default null
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare updated public.appointments%rowtype;
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' then
    raise exception 'Acesso administrativo necessário';
  end if;
  if not approved and nullif(trim(rejection_reason), '') is null then
    raise exception 'Informe o motivo da recusa';
  end if;
  update public.appointments set
    payment_status = case when approved then 'confirmado' else 'recusado' end,
    status = case when approved then 'confirmado' else 'cancelado' end,
    reservation_paid = approved,
    payment_reviewed_at = now(), payment_reviewed_by = auth.uid(),
    payment_rejection_reason = case when approved then null else rejection_reason end,
    payment_rejection_notes = case when approved then null else rejection_notes end,
    cancelled_at = case when approved then cancelled_at else now() end,
    cancelled_by = case when approved then cancelled_by else 'admin_pagamento' end,
    reason = case when approved then reason else concat_ws(' — ', rejection_reason, rejection_notes) end
  where id = target_appointment_id and payment_status = 'em_analise'
  returning * into updated;
  if not found then raise exception 'Pagamento não encontrado ou já analisado'; end if;
  insert into public.request_activity(request_type, request_id, action, description, performed_by)
  values ('pagamento', target_appointment_id::text, case when approved then 'confirmado' else 'recusado' end,
    case when approved then 'Pagamento confirmado pela administração.' else concat('Pagamento recusado: ', rejection_reason) end, auth.uid());
  insert into public.admin_notifications(appointment_id, type, title, message, read_at)
  values (target_appointment_id::text, case when approved then 'payment_approved' else 'payment_rejected' end,
    case when approved then 'Pagamento confirmado' else 'Pagamento recusado' end,
    concat(updated.customer_name, ' — ', updated.appointment_date, ' às ', updated.appointment_time), now());
  return to_jsonb(updated);
end $$;

create or replace function public.admin_review_booking_request(
  target_request_id uuid, action_name text, target_date date default null,
  target_time text default null, admin_text text default null, refusal_reason text default null
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare request_row public.booking_requests%rowtype; new_appointment uuid; target_end integer; start_minutes integer;
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'admin' then raise exception 'Acesso administrativo necessário'; end if;
  select * into request_row from public.booking_requests where id=target_request_id for update;
  if not found then raise exception 'Solicitação não encontrada'; end if;
  if action_name not in ('aprovar','sugerir','recusar') then raise exception 'Ação inválida'; end if;
  if action_name='recusar' and nullif(trim(refusal_reason),'') is null then raise exception 'Informe o motivo'; end if;
  if action_name in ('aprovar','sugerir') then
    target_date := coalesce(target_date, request_row.appointment_date);
    target_time := coalesce(target_time, request_row.appointment_time);
    start_minutes := split_part(target_time,':',1)::int*60 + split_part(target_time,':',2)::int;
    target_end := start_minutes + coalesce(request_row.total_duration_minutes, request_row.duration_minutes);
    if extract(dow from target_date) in (0,4) then raise exception 'O estúdio não atende neste dia'; end if;
    if start_minutes < 480 or target_end > (case when extract(dow from target_date)=6 then 900 else 1080 end) then raise exception 'Horário fora do expediente'; end if;
    if start_minutes < (case when extract(dow from target_date)=6 then 780 else 810 end) and target_end > 720 then raise exception 'O atendimento atravessa o intervalo'; end if;
    if exists(select 1 from public.appointments a where a.appointment_date=target_date and a.status<>'cancelado'
      and start_minutes < split_part(coalesce(a.end_time, a.appointment_time),':',1)::int*60+split_part(coalesce(a.end_time,a.appointment_time),':',2)::int
      and target_end > split_part(a.appointment_time,':',1)::int*60+split_part(a.appointment_time,':',2)::int) then raise exception 'Horário já ocupado'; end if;
    if exists(select 1 from public.agenda_blocks b where b.block_date=target_date
      and start_minutes < extract(hour from b.end_time)*60+extract(minute from b.end_time)
      and target_end > extract(hour from b.start_time)*60+extract(minute from b.start_time)) then raise exception 'Horário bloqueado'; end if;
  end if;
  if action_name='aprovar' then
    insert into public.appointments(service_id,service_name,customer_name,phone,email,notes,appointment_date,appointment_time,end_time,status,reservation_paid,duration_minutes,image_authorization,service_price,reservation_amount,remaining_amount,total_duration_minutes,payment_proof,payment_status)
    values(request_row.service_id,request_row.service_name,request_row.customer_name,request_row.phone,request_row.email,request_row.notes,target_date,target_time,
      lpad((target_end/60)::text,2,'0')||':'||lpad((target_end%60)::text,2,'0'),'aguardando_pagamento',false,request_row.duration_minutes,request_row.image_authorization,
      request_row.total_price,request_row.reservation_amount,request_row.remaining_amount,request_row.total_duration_minutes,request_row.payment_proof,'aguardando_pagamento') returning id into new_appointment;
  end if;
  update public.booking_requests set status=case action_name when 'aprovar' then 'aprovado' when 'sugerir' then 'aguardando_resposta_cliente' else 'recusado' end,
    proposed_date=case when action_name='sugerir' then target_date else null end, proposed_time=case when action_name='sugerir' then target_time else null end,
    admin_message=admin_text,rejection_reason=refusal_reason,reviewed_at=now(),reviewed_by=auth.uid() where id=target_request_id returning * into request_row;
  insert into public.request_activity(request_type,request_id,action,description,performed_by) values('encaixe',target_request_id::text,action_name,coalesce(admin_text,refusal_reason),auth.uid());
  return to_jsonb(request_row)||jsonb_build_object('appointment_id',new_appointment);
end $$;

create or replace function public.admin_review_reschedule_request(
  target_request_id uuid, action_name text, target_date date default null,
  target_time text default null, admin_text text default null
) returns jsonb
language plpgsql security definer set search_path = public
as $$
declare req public.reschedule_requests%rowtype; appt public.appointments%rowtype; duration integer; ending integer; starting integer;
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role','') <> 'admin' then raise exception 'Acesso administrativo necessário'; end if;
  select * into req from public.reschedule_requests where id=target_request_id for update;
  select * into appt from public.appointments where id=req.appointment_id for update;
  if req.id is null or appt.id is null then raise exception 'Remarcação não encontrada'; end if;
  if action_name in ('aprovar','sugerir') then
    target_date:=coalesce(target_date,req.requested_date); target_time:=coalesce(target_time,req.requested_time);
    duration:=coalesce(appt.total_duration_minutes,appt.duration_minutes); starting:=split_part(target_time,':',1)::int*60+split_part(target_time,':',2)::int; ending:=starting+duration;
    if exists(select 1 from public.appointments a where a.id<>appt.id and a.appointment_date=target_date and a.status<>'cancelado'
      and starting<split_part(coalesce(a.end_time,a.appointment_time),':',1)::int*60+split_part(coalesce(a.end_time,a.appointment_time),':',2)::int
      and ending>split_part(a.appointment_time,':',1)::int*60+split_part(a.appointment_time,':',2)::int) then raise exception 'Horário já ocupado'; end if;
  end if;
  if action_name='aprovar' then update public.appointments set appointment_date=target_date,appointment_time=target_time,end_time=lpad((ending/60)::text,2,'0')||':'||lpad((ending%60)::text,2,'0') where id=appt.id; end if;
  update public.reschedule_requests set status=case action_name when 'aprovar' then 'aprovado' when 'sugerir' then 'aguardando_resposta_cliente' else 'recusado' end,
    proposed_date=case when action_name='sugerir' then target_date else null end,proposed_time=case when action_name='sugerir' then target_time else null end,
    admin_message=admin_text,reviewed_by=auth.uid(),reviewed_at=now() where id=target_request_id returning * into req;
  insert into public.request_activity(request_type,request_id,action,description,performed_by) values('remarcacao',target_request_id::text,action_name,admin_text,auth.uid());
  return to_jsonb(req);
end $$;

revoke all on function public.admin_review_payment(uuid,boolean,text,text) from public;
revoke all on function public.admin_review_booking_request(uuid,text,date,text,text,text) from public;
revoke all on function public.admin_review_reschedule_request(uuid,text,date,text,text) from public;
grant execute on function public.admin_review_payment(uuid,boolean,text,text) to authenticated;
grant execute on function public.admin_review_booking_request(uuid,text,date,text,text,text) to authenticated;
grant execute on function public.admin_review_reschedule_request(uuid,text,date,text,text) to authenticated;
