alter table public.admin_notifications add column if not exists category text not null default 'sistema';
alter table public.admin_notifications add column if not exists action_url text;
alter table public.admin_notifications add column if not exists event_key text;
create unique index if not exists admin_notifications_event_key_unique on public.admin_notifications(event_key) where event_key is not null;
create table if not exists public.admin_notification_reads(notification_id bigint not null references public.admin_notifications(id) on delete cascade,admin_user_id uuid not null references auth.users(id) on delete cascade,read_at timestamptz not null default now(),primary key(notification_id,admin_user_id));
alter table public.admin_notification_reads enable row level security;
drop policy if exists "Admins manage own notification reads" on public.admin_notification_reads;
create policy "Admins manage own notification reads" on public.admin_notification_reads for all to authenticated using(public.is_admin() and admin_user_id=auth.uid()) with check(public.is_admin() and admin_user_id=auth.uid());
create or replace function public.get_admin_notification_center(page_size integer default 20,page_offset integer default 0) returns jsonb language plpgsql security definer set search_path=public as $$ declare result jsonb; begin if not public.is_admin() then raise exception 'Acesso negado'; end if; select jsonb_build_object('unread_count',(select count(*) from public.admin_notifications n where not exists(select 1 from public.admin_notification_reads r where r.notification_id=n.id and r.admin_user_id=auth.uid())),'items',coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)) into result from (select n.id,n.appointment_id,n.type,n.title,n.message,n.category,n.action_url,n.created_at,(r.read_at is not null) is_read from public.admin_notifications n left join public.admin_notification_reads r on r.notification_id=n.id and r.admin_user_id=auth.uid() order by n.created_at desc limit greatest(1,least(page_size,50)) offset greatest(page_offset,0)) x; return result; end $$;
create or replace function public.mark_admin_notification_read(target_id bigint default null) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'Acesso negado'; end if; insert into public.admin_notification_reads(notification_id,admin_user_id) select id,auth.uid() from public.admin_notifications where target_id is null or id=target_id on conflict do nothing; end $$;
revoke all on function public.get_admin_notification_center(integer,integer) from public; revoke all on function public.mark_admin_notification_read(bigint) from public;
grant execute on function public.get_admin_notification_center(integer,integer) to authenticated; grant execute on function public.mark_admin_notification_read(bigint) to authenticated;
update public.admin_notifications set category=case when type ilike '%payment%' then 'pagamento' when type ilike '%cancel%' then 'cancelamento' when type ilike '%resched%' then 'remarcação' when type ilike '%fit%' or type ilike '%booking%' then 'encaixe' when type ilike '%schedule%' then 'agenda mensal' else 'agendamento' end,action_url=case when type ilike '%payment%' then '/admin/solicitacoes?tab=pagamentos&request='||appointment_id when type ilike '%cancel%' then '/admin/solicitacoes?tab=cancelamentos&request='||appointment_id when type ilike '%schedule%' then '/admin#monthly-schedule' else '/admin/agenda' end where action_url is null;
alter table public.appointments add column if not exists completed_at timestamptz;
alter table public.appointments add column if not exists completed_by uuid references auth.users(id) on delete set null;
alter table public.appointments add column if not exists review_email_sent_at timestamptz;
insert into public.notification_preferences(id,email_enabled,priority) values('post_service',true,'normal') on conflict(id) do nothing;
insert into public.email_templates(id,subject,title,subtitle,body,signature,button_text,button_url,required_variables) values('post_service','Obrigada pela confiança! 🤎','Obrigada pela confiança! 🤎','Esperamos que você tenha aproveitado seu momento de cuidado.','<p>Olá {{customer_name}}, foi um prazer cuidar de você.</p>','Thaís Santos Beauty Studio<br>Cuidando da sua beleza com carinho. 🤎','Avaliar atendimento','{{review_url}}',array['{{customer_name}}','{{review_url}}']) on conflict(id) do update set subject=excluded.subject,title=excluded.title,subtitle=excluded.subtitle,body=excluded.body,button_text=excluded.button_text,button_url=excluded.button_url,required_variables=excluded.required_variables,updated_at=now();
create or replace function public.prepare_post_service_emails() returns void language plpgsql security definer set search_path=public as $$ declare a record; review_url text; begin select nullif(trim(public_data->>'google_review_url'),'') into review_url from public.studio_settings where id='main'; for a in select * from public.appointments where status='concluido' and review_email_sent_at is null and completed_at is not null and completed_at<=now()-interval '2 hours' loop perform public.enqueue_automation_email(a.email,'post_service','post_service','post-service:'||a.id,jsonb_build_object('customer_name',a.customer_name,'review_url',coalesce(review_url,'')),jsonb_build_object('appointment_id',a.id,'kind','post_service')); end loop; end $$;
create or replace function public.complete_automation_email(job_id bigint,was_sent boolean,error_text text default null) returns void language plpgsql security definer set search_path=public as $$ declare job public.automation_email_outbox%rowtype; begin select * into job from public.automation_email_outbox where id=job_id for update; if not found then return; end if; if was_sent then update public.automation_email_outbox set status='sent',sent_at=now(),last_error=null,updated_at=now() where id=job_id; if job.metadata->>'kind'='reminder_24h' then update public.appointments set reminder_sent_at=now() where id=(job.metadata->>'appointment_id')::uuid; end if; if job.metadata->>'kind'='post_service' then update public.appointments set review_email_sent_at=now() where id=(job.metadata->>'appointment_id')::uuid; end if; if job.metadata->>'kind'='promotion' then insert into public.promotion_email_history(promotion_id,customer_id,recipient,outbox_id) values((job.metadata->>'promotion_id')::uuid,(job.metadata->>'customer_id')::uuid,job.recipient,job.id) on conflict do nothing; end if; elsif error_text='disabled' then update public.automation_email_outbox set status='skipped',last_error=error_text,updated_at=now() where id=job_id; else update public.automation_email_outbox set status=case when attempts>=5 then 'failed' else 'pending' end,last_error=left(error_text,1000),next_attempt_at=now()+make_interval(mins=>least(60,attempts*10)),updated_at=now() where id=job_id; end if; end $$;
do $$ begin if exists(select 1 from pg_available_extensions where name='pg_cron') then create extension if not exists pg_cron; if not exists(select 1 from cron.job where jobname='beautyflow-post-service-preparation') then perform cron.schedule('beautyflow-post-service-preparation','20 * * * *','select public.prepare_post_service_emails();'); end if; end if; exception when others then raise notice 'Job pós-atendimento não pôde ser criado: %',sqlerrm; end $$;

insert into public.notification_preferences(id,email_enabled,priority) values('admin_cancellation',true,'high'),('admin_reschedule',true,'high'),('admin_fit',true,'high') on conflict(id) do nothing;
insert into public.email_templates(id,subject,title,subtitle,body,signature,button_text,button_url,required_variables) values
('admin_cancellation','Um horário foi cancelado','Um horário foi cancelado','O horário já foi liberado novamente na agenda.','<p>{{customer_name}} cancelou o atendimento de {{appointment_date}} às {{appointment_time}}.</p>','Thaís Santos Beauty Studio<br>Cuidando da sua beleza com carinho. 🤎','Ver cancelamento','{{site_url}}/admin/solicitacoes?tab=cancelamentos&request={{request_id}}',array['{{customer_name}}','{{appointment_date}}','{{appointment_time}}','{{site_url}}','{{request_id}}']),
('admin_reschedule','Nova solicitação de remarcação','Nova solicitação de remarcação','A cliente gostaria de escolher uma nova data.','<p>{{customer_name}} enviou uma solicitação de remarcação.</p>','Thaís Santos Beauty Studio<br>Cuidando da sua beleza com carinho. 🤎','Analisar remarcação','{{site_url}}/admin/solicitacoes?tab=remarcacoes&request={{request_id}}',array['{{customer_name}}','{{site_url}}','{{request_id}}']),
('admin_fit','Uma cliente pediu um encaixe','Uma cliente pediu um encaixe','Confira a preferência informada e sugira um horário.','<p>{{customer_name}} enviou uma solicitação de encaixe.</p>','Thaís Santos Beauty Studio<br>Cuidando da sua beleza com carinho. 🤎','Analisar encaixe','{{site_url}}/admin/solicitacoes?tab=encaixes&request={{request_id}}',array['{{customer_name}}','{{site_url}}','{{request_id}}'])
on conflict(id) do update set subject=excluded.subject,title=excluded.title,subtitle=excluded.subtitle,body=excluded.body,button_text=excluded.button_text,button_url=excluded.button_url,required_variables=excluded.required_variables,updated_at=now();

update public.email_templates set title='Recebemos seu comprovante',subtitle='Agora faremos a conferência do pagamento.' where id='payment_review';
update public.email_templates set title='Tudo certo com o seu pagamento!',subtitle='Seu atendimento está confirmado.' where id='payment_confirmed';
update public.email_templates set title='Precisamos revisar seu pagamento',subtitle='Confira o motivo e envie um novo comprovante.' where id='payment_refused';
update public.email_templates set title='Seu cancelamento foi concluído',subtitle='O horário foi liberado conforme solicitado.' where id='cancellation';
update public.email_templates set title='Seu atendimento está chegando',subtitle='Amanhã estaremos esperando por você.' where id='reminder_24h';
update public.email_templates set title='Seu dia no Beauty Studio',subtitle='Veja os atendimentos e pendências de hoje.',button_text='Abrir painel',button_url='{{site_url}}/admin' where id='daily_summary';
update public.email_templates set title='A agenda do próximo mês precisa de atenção',subtitle='Revise os horários e libere novas marcações.',button_text='Revisar agenda',button_url='{{site_url}}/admin#monthly-schedule' where id='schedule_release';

create or replace function public.notify_admin_domain_events() returns trigger language plpgsql security definer set search_path=public as $$ declare key text; category_value text; title_value text; message_value text; url_value text; begin
  if tg_table_name='appointments' then
    if tg_op='INSERT' then key:='appointment-created:'||new.id;category_value:='agendamento';title_value:='Novo agendamento';message_value:=new.customer_name;url_value:='/admin/agenda?date='||new.appointment_date;
    elsif new.payment_status is distinct from old.payment_status and new.payment_status in('confirmado','recusado') then key:='payment-status:'||new.id||':'||new.payment_status;category_value:='pagamento';title_value:=case when new.payment_status='confirmado' then 'Pagamento aprovado' else 'Pagamento recusado' end;message_value:=new.customer_name;url_value:='/admin/solicitacoes?tab=pagamentos&request='||new.id;
    elsif new.status is distinct from old.status and new.status='cancelado' then key:='appointment-cancelled:'||new.id;category_value:='cancelamento';title_value:='Um horário foi cancelado';message_value:=new.customer_name;url_value:='/admin/solicitacoes?tab=cancelamentos&request='||new.id; perform public.enqueue_automation_email('admin@invalid.local','admin_cancellation','admin_cancellation','admin-cancellation:'||new.id,jsonb_build_object('customer_name',new.customer_name,'appointment_date',to_char(new.appointment_date,'DD/MM/YYYY'),'appointment_time',left(new.appointment_time,5),'request_id',new.id),jsonb_build_object('requires_admin_email',true,'appointment_id',new.id)); if coalesce(new.cancelled_by,'') in ('cliente_area','cliente_link_email') then return new; end if;
    else return new; end if;
  elsif tg_table_name='booking_requests' then key:='fit:'||new.id||':'||new.status;category_value:='encaixe';title_value:=case when tg_op='INSERT' then 'Novo pedido de encaixe' when new.status='expirado' then 'Proposta de encaixe expirada' else 'Encaixe atualizado' end;message_value:=new.customer_name;url_value:='/admin/solicitacoes?tab=encaixes&request='||new.id; if tg_op='INSERT' then perform public.enqueue_automation_email('admin@invalid.local','admin_fit','admin_fit','admin-fit:'||new.id,jsonb_build_object('customer_name',new.customer_name,'request_id',new.id),jsonb_build_object('requires_admin_email',true)); end if;
  else key:='reschedule:'||new.id||':'||new.status;category_value:='remarcação';title_value:=case when tg_op='INSERT' then 'Novo pedido de remarcação' else 'Remarcação atualizada' end;message_value:=coalesce((select customer_name from public.appointments where id=new.appointment_id),'Cliente');url_value:='/admin/solicitacoes?tab=remarcacoes&request='||new.id; if tg_op='INSERT' then perform public.enqueue_automation_email('admin@invalid.local','admin_reschedule','admin_reschedule','admin-reschedule:'||new.id,jsonb_build_object('customer_name',message_value,'request_id',new.id),jsonb_build_object('requires_admin_email',true)); end if; end if;
  insert into public.admin_notifications(appointment_id,type,title,message,category,action_url,event_key) values(coalesce(new.id::text,null),category_value,title_value,message_value,category_value,url_value,key) on conflict(event_key) where event_key is not null do nothing; return new;
end $$;
drop trigger if exists notify_admin_appointment_events on public.appointments; create trigger notify_admin_appointment_events after insert or update of status,payment_status on public.appointments for each row execute function public.notify_admin_domain_events();
-- Encaixes e remarcações já geram notificações nas RPCs de domínio aplicadas.
-- Não adicionamos triggers paralelos para evitar dois registros do mesmo evento.

create or replace function public.record_appointment_completion() returns trigger language plpgsql security definer set search_path=public as $$ begin
  if new.status='concluido' and old.status is distinct from new.status then
    new.completed_at:=coalesce(new.completed_at,now()); new.completed_by:=coalesce(new.completed_by,auth.uid());
    insert into public.request_activity(request_type,request_id,action,description,performed_by)
    values('agendamento',new.id::text,'concluido','Atendimento marcado como concluído.',auth.uid());
  end if; return new;
end $$;
drop trigger if exists record_appointment_completion_trigger on public.appointments;
create trigger record_appointment_completion_trigger before update of status on public.appointments for each row execute function public.record_appointment_completion();
