create table if not exists public.email_delivery_logs (
  id bigint generated by default as identity primary key,
  recipient text not null,
  template_id text not null,
  preference_id text not null,
  event_key text not null,
  priority text not null default 'normal',
  status text not null check (status in ('sent','error','skipped')),
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.automation_email_outbox (
  id bigint generated by default as identity primary key,
  recipient text not null,
  template_id text not null,
  preference_id text not null,
  event_key text not null unique,
  priority text not null default 'normal' check (priority in ('low','normal','high')),
  variables jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','sent','skipped','failed')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by text,
  last_error text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promotion_email_history (
  id bigint generated by default as identity primary key,
  promotion_id uuid not null references public.promotions(id) on delete cascade,
  customer_id uuid not null references auth.users(id) on delete cascade,
  recipient text not null,
  outbox_id bigint references public.automation_email_outbox(id) on delete set null,
  sent_at timestamptz not null default now(),
  unique (promotion_id, customer_id)
);

create table if not exists public.daily_content_history (
  local_date date primary key,
  verse text not null,
  created_at timestamptz not null default now()
);

alter table public.appointments add column if not exists reminder_sent_at timestamptz;
create index if not exists automation_outbox_pending_idx on public.automation_email_outbox(status, next_attempt_at, priority);
create index if not exists email_delivery_logs_event_idx on public.email_delivery_logs(event_key, created_at desc);

alter table public.email_delivery_logs enable row level security;
alter table public.automation_email_outbox enable row level security;
alter table public.promotion_email_history enable row level security;
alter table public.daily_content_history enable row level security;

create policy "Admins read email delivery logs" on public.email_delivery_logs for select to authenticated using (public.is_admin());
create policy "Admins read automation outbox" on public.automation_email_outbox for select to authenticated using (public.is_admin());
create policy "Admins read promotion email history" on public.promotion_email_history for select to authenticated using (public.is_admin());
create policy "Admins read daily content history" on public.daily_content_history for select to authenticated using (public.is_admin());

insert into public.notification_preferences(id, email_enabled, priority) values
 ('welcome', true, 'normal'), ('payment_analysis', true, 'high'),
 ('appointment_confirmed', true, 'high'), ('reminder_24h', true, 'high'),
 ('reschedule_status', true, 'normal'), ('fit_status', true, 'normal'),
 ('promotion', false, 'low'), ('daily_summary', true, 'normal'),
 ('schedule_release', true, 'high')
on conflict (id) do nothing;

insert into public.email_templates(id,subject,title,body,signature,required_variables) values
 ('automation_fallback','Atualização do Beauty Studio','Temos uma atualização para você','Olá {{customer_name}}, acesse o BeautyFlow para consultar os detalhes.','Thaís Santos Beauty Studio','{customer_name}'),
 ('reschedule_approved','Remarcação aprovada','Seu novo horário foi confirmado','Olá {{customer_name}}, seu atendimento foi remarcado para {{appointment_date}} às {{appointment_time}}.','Thaís Santos Beauty Studio','{customer_name,appointment_date,appointment_time}'),
 ('reschedule_rejected','Solicitação de remarcação analisada','Não foi possível remarcar','Olá {{customer_name}}, não foi possível aprovar a remarcação solicitada. {{reason}}','Thaís Santos Beauty Studio','{customer_name}'),
 ('reschedule_proposed','Novo horário sugerido','Temos uma nova sugestão de horário','Olá {{customer_name}}, sugerimos {{appointment_date}} às {{appointment_time}}. Acesse seu espaço para responder.','Thaís Santos Beauty Studio','{customer_name,appointment_date,appointment_time}'),
 ('fit_approved','Encaixe aprovado','Temos um horário para você','Olá {{customer_name}}, o encaixe foi aprovado para {{appointment_date}} às {{appointment_time}}.','Thaís Santos Beauty Studio','{customer_name,appointment_date,appointment_time}'),
 ('fit_rejected','Solicitação de encaixe analisada','Não foi possível realizar o encaixe','Olá {{customer_name}}, sua solicitação de encaixe não pôde ser aprovada. {{reason}}','Thaís Santos Beauty Studio','{customer_name}'),
 ('daily_summary','Resumo diário — {{summary_date}}','{{greeting}}, Thaís','Agenda: {{appointments}} atendimento(s). Pagamentos em análise: {{payments}}. Cancelamentos: {{cancellations}}. Encaixes: {{fits}}. Remarcações: {{reschedules}}. Novas clientes: {{new_customers}}.<br><br>{{verse}}','BeautyFlow','{summary_date,greeting,appointments,payments,cancellations,fits,reschedules,new_customers,verse}'),
 ('schedule_release','Lembrete de liberação da agenda','A agenda do próximo mês ainda está fechada','A agenda de {{next_month}} ainda não foi liberada para as clientes.','BeautyFlow','{next_month}'),
 ('promotion','{{promotion_title}}','Uma novidade para você','Olá {{customer_name}}, {{promotion_description}} {{promotion_link}}','Thaís Santos Beauty Studio','{customer_name,promotion_title,promotion_description}'),
 ('signup','Bem-vinda ao BeautyFlow','Cadastro concluído com sucesso! 🤎','Olá {{customer_name}}, seu espaço está pronto para receber você.','Thaís Santos Beauty Studio','{customer_name}'),
 ('payment_review','Pagamento em análise','Recebemos seu comprovante','Olá {{customer_name}}, seu comprovante foi recebido e será analisado.','Thaís Santos Beauty Studio','{customer_name}'),
 ('payment_confirmed','Pagamento confirmado','Agendamento confirmado','Olá {{customer_name}}, seu atendimento de {{service_name}} será em {{appointment_date}} às {{appointment_time}}.','Thaís Santos Beauty Studio','{customer_name,service_name,appointment_date,appointment_time}'),
 ('payment_refused','Comprovante não aprovado','Precisamos de um novo comprovante','Olá {{customer_name}}, não foi possível validar o comprovante enviado.','Thaís Santos Beauty Studio','{customer_name}'),
 ('appointment_confirmed','Agendamento confirmado','Está tudo certo','Olá {{customer_name}}, esperamos você em {{appointment_date}} às {{appointment_time}}.','Thaís Santos Beauty Studio','{customer_name,appointment_date,appointment_time}'),
 ('cancellation','Agendamento cancelado','Cancelamento recebido','Olá {{customer_name}}, o atendimento de {{service_name}} foi cancelado.','Thaís Santos Beauty Studio','{customer_name,service_name}'),
 ('reminder_24h','Seu atendimento é amanhã','Lembrete do seu atendimento','Olá {{customer_name}}, esperamos você amanhã às {{appointment_time}} para {{service_name}}.','Thaís Santos Beauty Studio','{customer_name,appointment_time,service_name}')
on conflict (id) do update set required_variables=excluded.required_variables;

create or replace function public.enqueue_automation_email(
  target_recipient text, target_template text, target_preference text,
  target_event_key text, target_variables jsonb default '{}'::jsonb,
  target_metadata jsonb default '{}'::jsonb
) returns bigint language plpgsql security definer set search_path=public as $$
declare result bigint; selected_priority text;
begin
  if nullif(trim(target_recipient),'') is null then return null; end if;
  select coalesce(priority,'normal') into selected_priority from public.notification_preferences where id=target_preference;
  insert into public.automation_email_outbox(recipient,template_id,preference_id,event_key,priority,variables,metadata)
  values(lower(trim(target_recipient)),target_template,target_preference,target_event_key,coalesce(selected_priority,'normal'),coalesce(target_variables,'{}'),coalesce(target_metadata,'{}'))
  on conflict(event_key) do nothing returning id into result;
  return result;
end $$;

create or replace function public.claim_automation_email_outbox(batch_size integer default 50, worker_name text default 'worker')
returns setof public.automation_email_outbox language plpgsql security definer set search_path=public as $$
begin
  return query with claimed as (
    select id from public.automation_email_outbox
    where (status='pending' or (status='processing' and locked_at<now()-interval '15 minutes'))
      and attempts<5 and next_attempt_at<=now()
    order by case priority when 'high' then 1 when 'normal' then 2 else 3 end, created_at
    for update skip locked limit greatest(1,least(batch_size,100))
  ) update public.automation_email_outbox o set status='processing',attempts=attempts+1,locked_at=now(),locked_by=worker_name,updated_at=now()
    from claimed where o.id=claimed.id returning o.*;
end $$;

create or replace function public.complete_automation_email(job_id bigint, was_sent boolean, error_text text default null)
returns void language plpgsql security definer set search_path=public as $$
declare job public.automation_email_outbox%rowtype;
begin
  select * into job from public.automation_email_outbox where id=job_id for update;
  if not found then return; end if;
  if was_sent then
    update public.automation_email_outbox set status='sent',sent_at=now(),last_error=null,updated_at=now() where id=job_id;
    if job.metadata->>'kind'='reminder_24h' then update public.appointments set reminder_sent_at=now() where id=(job.metadata->>'appointment_id')::uuid; end if;
    if job.metadata->>'kind'='promotion' then
      insert into public.promotion_email_history(promotion_id,customer_id,recipient,outbox_id)
      values((job.metadata->>'promotion_id')::uuid,(job.metadata->>'customer_id')::uuid,job.recipient,job.id) on conflict do nothing;
    end if;
  elsif error_text='disabled' then
    update public.automation_email_outbox set status='skipped',last_error=error_text,updated_at=now() where id=job_id;
  else
    update public.automation_email_outbox set status=case when attempts>=5 then 'failed' else 'pending' end,last_error=left(error_text,1000),next_attempt_at=now()+make_interval(mins=>least(60,attempts*10)),updated_at=now() where id=job_id;
  end if;
end $$;

create or replace function public.automation_appointment_email_trigger() returns trigger language plpgsql security definer set search_path=public as $$
declare vars jsonb; names text;
begin
  select coalesce(string_agg(service_name,', '),new.service_name,'Atendimento') into names from public.appointment_services where appointment_id=new.id;
  vars:=jsonb_build_object('customer_name',new.customer_name,'appointment_date',to_char(new.appointment_date,'DD/MM/YYYY'),'appointment_time',left(new.appointment_time,5),'service_name',names);
  if tg_op='INSERT' and new.payment_status='em_analise' then perform public.enqueue_automation_email(new.email,'payment_review','payment_analysis','payment-review:'||new.id,vars,jsonb_build_object('appointment_id',new.id)); end if;
  if tg_op='UPDATE' and new.payment_status is distinct from old.payment_status then
    if new.payment_status in('aprovado','pago','approved') then perform public.enqueue_automation_email(new.email,'payment_confirmed','payment_proof','payment-approved:'||new.id,vars,jsonb_build_object('appointment_id',new.id)); end if;
    if new.payment_status in('recusado','refused','rejeitado') then perform public.enqueue_automation_email(new.email,'payment_refused','payment_refused','payment-rejected:'||new.id,vars,jsonb_build_object('appointment_id',new.id)); end if;
  end if;
  if tg_op='UPDATE' and new.status is distinct from old.status then
    if new.status in('confirmado','confirmed') then perform public.enqueue_automation_email(new.email,'appointment_confirmed','appointment_confirmed','appointment-confirmed:'||new.id,vars,jsonb_build_object('appointment_id',new.id)); end if;
    if new.status='cancelado' then perform public.enqueue_automation_email(new.email,'cancellation','cancellation','appointment-cancelled:'||new.id,vars,jsonb_build_object('appointment_id',new.id)); end if;
  end if;
  return new;
end $$;
drop trigger if exists automation_appointment_email on public.appointments;
create trigger automation_appointment_email after insert or update of status,payment_status on public.appointments for each row execute function public.automation_appointment_email_trigger();

create or replace function public.automation_signup_email_trigger() returns trigger language plpgsql security definer set search_path=public as $$
begin
  perform public.enqueue_automation_email(new.email,'signup','welcome','signup:'||new.id,jsonb_build_object('customer_name',coalesce(new.raw_user_meta_data->>'name',new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1))),jsonb_build_object('user_id',new.id));
  return new;
end $$;
drop trigger if exists automation_signup_email on auth.users;
create trigger automation_signup_email after insert on auth.users for each row execute function public.automation_signup_email_trigger();

create or replace function public.automation_request_email_trigger() returns trigger language plpgsql security definer set search_path=public as $$
declare template text; vars jsonb;
begin
  if tg_op<>'UPDATE' or new.status is not distinct from old.status then return new; end if;
  vars:=jsonb_build_object('customer_name',new.customer_name,'appointment_date',to_char(coalesce(new.proposed_date,new.appointment_date),'DD/MM/YYYY'),'appointment_time',left(coalesce(new.proposed_time,new.appointment_time),5),'reason',coalesce(new.rejection_reason,new.admin_message,''));
  template:=case when new.status='recusado' then 'fit_rejected' when new.status in('aguardando_resposta_cliente','aprovado') then 'fit_approved' else null end;
  if template is not null then perform public.enqueue_automation_email(new.email,template,'fit_status','fit-'||new.status||':'||new.id,vars,jsonb_build_object('request_id',new.id)); end if;
  return new;
end $$;
drop trigger if exists automation_fit_email on public.booking_requests;
create trigger automation_fit_email after update of status on public.booking_requests for each row execute function public.automation_request_email_trigger();

create or replace function public.automation_reschedule_email_trigger() returns trigger language plpgsql security definer set search_path=public as $$
declare a public.appointments%rowtype; template text; vars jsonb;
begin
  if new.status is not distinct from old.status then return new; end if;
  select * into a from public.appointments where id=new.appointment_id;
  template:=case when new.status in('aprovado','approved') then 'reschedule_approved' when new.status in('recusado','rejected') then 'reschedule_rejected' when new.status in('aguardando_resposta_cliente','proposto') then 'reschedule_proposed' else null end;
  vars:=jsonb_build_object('customer_name',a.customer_name,'appointment_date',to_char(coalesce(new.proposed_date,new.requested_date),'DD/MM/YYYY'),'appointment_time',left(coalesce(new.proposed_time,new.requested_time),5),'reason',coalesce(new.rejection_reason,new.admin_message,''));
  if template is not null then perform public.enqueue_automation_email(a.email,template,'reschedule_status','reschedule-'||new.status||':'||new.id,vars,jsonb_build_object('request_id',new.id)); end if;
  return new;
end $$;
drop trigger if exists automation_reschedule_email on public.reschedule_requests;
create trigger automation_reschedule_email after update of status on public.reschedule_requests for each row execute function public.automation_reschedule_email_trigger();

create or replace function public.prepare_hourly_automation_emails() returns void language plpgsql security definer set search_path=public as $$
declare a record; local_now timestamp:=(now() at time zone 'America/Sao_Paulo'); local_today date:=(now() at time zone 'America/Sao_Paulo')::date; next_month date;
begin
  for a in select appointments.*,coalesce((select string_agg(service_name,', ') from public.appointment_services s where s.appointment_id=appointments.id),service_name,'Atendimento') names
    from public.appointments where status not in('cancelado','concluido','nao_compareceu','ausente') and reminder_sent_at is null
      and (appointment_date+appointment_time::time) between local_now+interval '23 hours' and local_now+interval '24 hours'
  loop
    perform public.enqueue_automation_email(a.email,'reminder_24h','reminder_24h','reminder-24h:'||a.id,
      jsonb_build_object('customer_name',a.customer_name,'appointment_time',left(a.appointment_time,5),'service_name',a.names),jsonb_build_object('kind','reminder_24h','appointment_id',a.id));
  end loop;
  perform public.create_monthly_schedule_release_reminders();
  if extract(day from local_today) in(20,25) or local_today=(date_trunc('month',local_today)+interval '1 month - 1 day')::date then
    next_month:=(date_trunc('month',local_today)+interval '1 month')::date;
    if not exists(select 1 from public.monthly_schedule_releases where year=extract(year from next_month)::int and month=extract(month from next_month)::int and status='released') then
      perform public.enqueue_automation_email('admin@invalid.local','schedule_release','schedule_release','schedule-release:'||local_today,
        jsonb_build_object('customer_name','Thaís','next_month',to_char(next_month,'MM/YYYY')),jsonb_build_object('kind','schedule_release','requires_admin_email',true));
    end if;
  end if;
end $$;

create or replace function public.prepare_promotion_emails() returns void language plpgsql security definer set search_path=public as $$
declare p record; c record;
begin
  for p in select * from public.promotions where active and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>=now()) loop
    for c in select * from public.customer_accounts where is_active and promotions_authorized and promotions_consent_at is not null and promotions_revoked_at is null loop
      if not exists(select 1 from public.promotion_email_history where promotion_id=p.id and customer_id=c.user_id) then
        perform public.enqueue_automation_email(c.email,'promotion','promotion','promotion:'||p.id||':'||c.user_id,
          jsonb_build_object('customer_name',coalesce(c.full_name,split_part(c.email,'@',1)),'promotion_title',p.title,'promotion_description',p.description,'promotion_link',coalesce(p.link,'')),jsonb_build_object('kind','promotion','promotion_id',p.id,'customer_id',c.user_id));
      end if;
    end loop;
  end loop;
end $$;

create or replace function public.prepare_daily_summary_email(admin_email text) returns void language plpgsql security definer set search_path=public as $$
declare d date:=(now() at time zone 'America/Sao_Paulo')::date; verse text; previous text; configured jsonb; hour_value integer:=extract(hour from now() at time zone 'America/Sao_Paulo');
begin
  select history.verse into previous from public.daily_content_history as history order by history.local_date desc limit 1;
  select private_data->'daily_verses' into configured from public.studio_settings where id='main';
  if jsonb_typeof(configured)='array' and jsonb_array_length(configured)>0 then select value#>>'{}' into verse from jsonb_array_elements(configured) where value#>>'{}' is distinct from previous order by random() limit 1; end if;
  verse:=coalesce(verse,case when previous is distinct from 'Tudo posso naquele que me fortalece. — Filipenses 4:13' then 'Tudo posso naquele que me fortalece. — Filipenses 4:13' else 'O Senhor é o meu pastor; nada me faltará. — Salmos 23:1' end);
  insert into public.daily_content_history(local_date,verse) values(d,verse) on conflict(local_date) do update set verse=excluded.verse;
  perform public.enqueue_automation_email(admin_email,'daily_summary','daily_summary','daily-summary:'||d,
    jsonb_build_object('customer_name','Thaís','summary_date',to_char(d,'DD/MM/YYYY'),'greeting',case when hour_value<12 then 'Bom dia' when hour_value<18 then 'Boa tarde' else 'Boa noite' end,
      'appointments',(select count(*) from public.appointments where appointment_date=d and status<>'cancelado'),
      'payments',(select count(*) from public.appointments where payment_status='em_analise'),
      'cancellations',(select count(*) from public.appointments where cancelled_at::date=d),
      'fits',(select count(*) from public.booking_requests where created_at::date=d),
      'reschedules',(select count(*) from public.reschedule_requests where created_at::date=d),
      'new_customers',(select count(*) from public.customer_accounts where created_at::date=d),'verse',verse),jsonb_build_object('kind','daily_summary'));
end $$;

revoke all on function public.enqueue_automation_email(text,text,text,text,jsonb,jsonb) from public;
revoke all on function public.claim_automation_email_outbox(integer,text) from public;
revoke all on function public.complete_automation_email(bigint,boolean,text) from public;
revoke all on function public.prepare_hourly_automation_emails() from public;
revoke all on function public.prepare_promotion_emails() from public;
revoke all on function public.prepare_daily_summary_email(text) from public;

do $$ begin
  if exists(select 1 from pg_available_extensions where name='pg_cron') then
    create extension if not exists pg_cron;
    if not exists(select 1 from cron.job where jobname='beautyflow-hourly-email-preparation') then perform cron.schedule('beautyflow-hourly-email-preparation','5 * * * *','select public.prepare_hourly_automation_emails();'); end if;
    if not exists(select 1 from cron.job where jobname='beautyflow-daily-promotion-preparation') then perform cron.schedule('beautyflow-daily-promotion-preparation','15 8 * * *','select public.prepare_promotion_emails();'); end if;
  end if;
exception when others then raise notice 'Jobs de e-mail não puderam ser criados: %',sqlerrm; end $$;
