create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(auth.jwt()->'app_metadata'->>'role','') = 'admin' $$;

create table if not exists public.promotions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  link text,
  active boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.promotions
  add column if not exists internal_name text,
  add column if not exists short_description text not null default '',
  add column if not exists full_description text not null default '',
  add column if not exists discount_type text not null default 'percentage',
  add column if not exists discount_value numeric(10,2),
  add column if not exists promotional_price numeric(10,2),
  add column if not exists status text not null default 'draft',
  add column if not exists usage_limit integer,
  add column if not exists usage_count integer not null default 0,
  add column if not exists highlight_home boolean not null default false,
  add column if not exists highlight_customer_area boolean not null default false,
  add column if not exists display_order integer not null default 0,
  add column if not exists button_text text not null default 'Ver promoção',
  add column if not exists button_target text not null default '/servicos',
  add column if not exists image_path text,
  add column if not exists apply_to_reservation_fee boolean not null default false,
  add column if not exists email_enabled boolean not null default false,
  add column if not exists applies_to_all_services boolean not null default false,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists ended_at timestamptz;

update public.promotions set
  internal_name = coalesce(nullif(internal_name,''), title),
  short_description = coalesce(nullif(short_description,''), description),
  full_description = coalesce(nullif(full_description,''), description),
  button_target = coalesce(nullif(button_target,''), link, '/servicos'),
  status = case when active then 'active' else coalesce(status,'draft') end
where internal_name is null or internal_name = '';

alter table public.promotions alter column internal_name set not null;
alter table public.promotions drop constraint if exists promotions_discount_type_check;
alter table public.promotions add constraint promotions_discount_type_check check (discount_type in ('percentage','fixed','promotional_price','benefit'));
alter table public.promotions drop constraint if exists promotions_status_check;
alter table public.promotions add constraint promotions_status_check check (status in ('draft','scheduled','active','paused','ended','expired'));
alter table public.promotions drop constraint if exists promotions_dates_check;
alter table public.promotions add constraint promotions_dates_check check (ends_at is null or starts_at is null or ends_at > starts_at);
alter table public.promotions drop constraint if exists promotions_usage_check;
alter table public.promotions add constraint promotions_usage_check check (usage_limit is null or usage_limit >= 1);

create table if not exists public.promotion_services (
  id bigint generated by default as identity primary key,
  promotion_id uuid not null references public.promotions(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(promotion_id, service_id)
);

create table if not exists public.promotion_activity (
  id bigint generated by default as identity primary key,
  promotion_id uuid not null references public.promotions(id) on delete cascade,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  performed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.appointments
  add column if not exists promotion_id uuid references public.promotions(id) on delete set null,
  add column if not exists original_service_price numeric(10,2),
  add column if not exists promotion_discount numeric(10,2) not null default 0;

alter table public.appointment_services
  add column if not exists promotion_id uuid references public.promotions(id) on delete set null,
  add column if not exists original_service_price numeric(10,2),
  add column if not exists promotion_discount numeric(10,2) not null default 0;

alter table public.customer_accounts
  add column if not exists promotions_consent_at timestamptz,
  add column if not exists promotions_revoked_at timestamptz;

alter table public.promotions enable row level security;
alter table public.promotion_services enable row level security;
alter table public.promotion_activity enable row level security;
drop policy if exists "Public can view active promotions" on public.promotions;
create policy "Public can view active promotions" on public.promotions for select using (
  public.is_admin() or (status='active' and coalesce(starts_at,now())<=now() and coalesce(ends_at,now()+interval '100 years')>=now() and (usage_limit is null or usage_count < usage_limit))
);
drop policy if exists "Admins manage promotions" on public.promotions;
create policy "Admins manage promotions" on public.promotions for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Public reads promotion services" on public.promotion_services;
create policy "Public reads promotion services" on public.promotion_services for select using (exists(select 1 from public.promotions p where p.id=promotion_id));
drop policy if exists "Admins manage promotion services" on public.promotion_services;
create policy "Admins manage promotion services" on public.promotion_services for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins read promotion activity" on public.promotion_activity;
create policy "Admins read promotion activity" on public.promotion_activity for select to authenticated using(public.is_admin());

create or replace function public.get_active_promotions(target text default null)
returns table(id uuid,title text,short_description text,full_description text,discount_type text,discount_value numeric,promotional_price numeric,starts_at timestamptz,ends_at timestamptz,button_text text,button_target text,image_path text,apply_to_reservation_fee boolean,applies_to_all_services boolean,service_ids bigint[])
language sql stable security definer set search_path=public as $$
  select p.id,p.title,p.short_description,p.full_description,p.discount_type,p.discount_value,p.promotional_price,p.starts_at,p.ends_at,p.button_text,p.button_target,p.image_path,p.apply_to_reservation_fee,p.applies_to_all_services,
    coalesce(array_agg(ps.service_id) filter(where ps.service_id is not null),'{}')
  from public.promotions p left join public.promotion_services ps on ps.promotion_id=p.id
  where p.status='active' and coalesce(p.starts_at,now())<=now() and coalesce(p.ends_at,now()+interval '100 years')>=now()
    and (p.usage_limit is null or p.usage_count<p.usage_limit)
    and (target is null or (target='home' and p.highlight_home) or (target='customer' and p.highlight_customer_area) or target='services')
  group by p.id order by p.display_order,p.created_at desc;
$$;

create or replace function public.admin_save_promotion(payload jsonb, target_id uuid default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare result_id uuid; service_value jsonb;
begin
  if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if;
  if coalesce(payload->>'internal_name','')='' or coalesce(payload->>'title','')='' then raise exception 'Nome e título são obrigatórios'; end if;
  if (payload->>'ends_at')::timestamptz <= (payload->>'starts_at')::timestamptz then raise exception 'A data final deve ser posterior à inicial'; end if;
  if payload->>'discount_type'='percentage' and ((payload->>'discount_value')::numeric<=0 or (payload->>'discount_value')::numeric>100) then raise exception 'Percentual deve estar entre 0 e 100'; end if;
  if target_id is null then
    insert into public.promotions(internal_name,title,short_description,full_description,discount_type,discount_value,promotional_price,starts_at,ends_at,status,usage_limit,highlight_home,highlight_customer_area,display_order,button_text,button_target,apply_to_reservation_fee,email_enabled,applies_to_all_services,created_by)
    values(payload->>'internal_name',payload->>'title',coalesce(payload->>'short_description',''),coalesce(payload->>'full_description',''),payload->>'discount_type',nullif(payload->>'discount_value','')::numeric,nullif(payload->>'promotional_price','')::numeric,(payload->>'starts_at')::timestamptz,(payload->>'ends_at')::timestamptz,coalesce(payload->>'status','draft'),nullif(payload->>'usage_limit','')::integer,coalesce((payload->>'highlight_home')::boolean,false),coalesce((payload->>'highlight_customer_area')::boolean,false),coalesce((payload->>'display_order')::integer,0),coalesce(payload->>'button_text','Ver promoção'),coalesce(payload->>'button_target','/servicos'),coalesce((payload->>'apply_to_reservation_fee')::boolean,false),coalesce((payload->>'email_enabled')::boolean,false),coalesce((payload->>'applies_to_all_services')::boolean,false),auth.uid()) returning id into result_id;
  else
    update public.promotions set internal_name=payload->>'internal_name',title=payload->>'title',short_description=coalesce(payload->>'short_description',''),full_description=coalesce(payload->>'full_description',''),discount_type=payload->>'discount_type',discount_value=nullif(payload->>'discount_value','')::numeric,promotional_price=nullif(payload->>'promotional_price','')::numeric,starts_at=(payload->>'starts_at')::timestamptz,ends_at=(payload->>'ends_at')::timestamptz,status=payload->>'status',usage_limit=nullif(payload->>'usage_limit','')::integer,highlight_home=(payload->>'highlight_home')::boolean,highlight_customer_area=(payload->>'highlight_customer_area')::boolean,display_order=(payload->>'display_order')::integer,button_text=payload->>'button_text',button_target=payload->>'button_target',apply_to_reservation_fee=(payload->>'apply_to_reservation_fee')::boolean,email_enabled=(payload->>'email_enabled')::boolean,applies_to_all_services=(payload->>'applies_to_all_services')::boolean,updated_at=now() where id=target_id returning id into result_id;
  end if;
  delete from public.promotion_services where promotion_id=result_id;
  if not coalesce((payload->>'applies_to_all_services')::boolean,false) then
    for service_value in select * from jsonb_array_elements(coalesce(payload->'service_ids','[]'::jsonb)) loop
      insert into public.promotion_services(promotion_id,service_id) select result_id,(service_value#>>'{}')::bigint from public.services where id=(service_value#>>'{}')::bigint and is_active;
    end loop;
  end if;
  insert into public.promotion_activity(promotion_id,action,performed_by,details) values(result_id,case when target_id is null then 'created' else 'updated' end,auth.uid(),payload);
  return result_id;
end $$;

create or replace function public.admin_change_promotion(target_id uuid,new_status text)
returns void language plpgsql security definer set search_path=public as $$ begin
 if not public.is_admin() then raise exception 'Acesso negado'; end if;
 if new_status not in ('active','paused','ended') then raise exception 'Status inválido'; end if;
 update public.promotions set status=new_status,active=(new_status='active'),ended_at=case when new_status='ended' then now() else ended_at end,updated_at=now() where id=target_id;
 insert into public.promotion_activity(promotion_id,action,performed_by) values(target_id,new_status,auth.uid());
end $$;

create or replace function public.admin_duplicate_promotion(target_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$ declare result uuid; begin
 if not public.is_admin() then raise exception 'Acesso negado'; end if;
 insert into public.promotions(internal_name,title,short_description,full_description,discount_type,discount_value,promotional_price,status,usage_count,highlight_home,highlight_customer_area,display_order,button_text,button_target,apply_to_reservation_fee,email_enabled,applies_to_all_services,created_by)
 select internal_name||' — Cópia',title,short_description,full_description,discount_type,discount_value,promotional_price,'draft',0,false,false,display_order,button_text,button_target,apply_to_reservation_fee,email_enabled,applies_to_all_services,auth.uid() from public.promotions where id=target_id returning id into result;
 insert into public.promotion_services(promotion_id,service_id) select result,service_id from public.promotion_services where promotion_id=target_id;
 insert into public.promotion_activity(promotion_id,action,performed_by,details) values(result,'duplicated',auth.uid(),jsonb_build_object('source',target_id)); return result;
end $$;

grant execute on function public.get_active_promotions(text) to anon,authenticated;
grant execute on function public.admin_save_promotion(jsonb,uuid) to authenticated;
grant execute on function public.admin_change_promotion(uuid,text) to authenticated;
grant execute on function public.admin_duplicate_promotion(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('promotion-media','promotion-media',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Public reads promotion media" on storage.objects;
create policy "Public reads promotion media" on storage.objects for select using(bucket_id='promotion-media');
drop policy if exists "Admins manage promotion media" on storage.objects;
create policy "Admins manage promotion media" on storage.objects for all to authenticated using(bucket_id='promotion-media' and public.is_admin()) with check(bucket_id='promotion-media' and public.is_admin());
