create extension if not exists pgcrypto;

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  service_id bigint,
  service_name text,
  customer_name text not null,
  phone text not null,
  email text not null,
  notes text,
  appointment_date date not null,
  appointment_time text not null,
  end_time text not null,
  status text not null default 'aguardando_aprovacao',
  payment_status text not null default 'em_analise',
  reservation_paid boolean not null default false,
  image_authorization boolean,
  reservation_policy_accepted boolean not null default false,
  service_price numeric(10, 2) not null default 0,
  reservation_amount numeric(10, 2) not null default 0,
  remaining_amount numeric(10, 2) not null default 0,
  payment_proof text,
  duration_minutes integer not null,
  total_duration_minutes integer not null,
  created_at timestamptz not null default now(),
  constraint appointments_positive_duration
    check (duration_minutes > 0 and total_duration_minutes > 0),
  constraint appointments_reservation_policy_accepted_check
    check (reservation_policy_accepted is true)
);

create table if not exists public.appointment_services (
  id bigint generated by default as identity primary key,
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  service_id bigint not null,
  service_name text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  service_price numeric(10, 2) not null default 0,
  reservation_amount numeric(10, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.booking_requests (
  id uuid primary key default gen_random_uuid(),
  service_id bigint,
  service_name text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  total_duration_minutes integer,
  customer_name text not null,
  phone text not null,
  email text not null,
  notes text,
  image_authorization boolean,
  appointment_date date not null,
  appointment_time text not null,
  status text not null default 'pendente',
  total_price numeric(10, 2),
  reservation_amount numeric(10, 2),
  remaining_amount numeric(10, 2),
  payment_proof text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

-- A área da cliente é criada antes do catálogo administrativo e já referencia
-- promoções. Esta definição mínima garante a recriação sequencial do banco; a
-- migração administrativa posterior adiciona os demais campos e políticas.
create table if not exists public.promotions (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  link text,
  active boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists appointments_date_idx
  on public.appointments (appointment_date);
create index if not exists appointment_services_appointment_id_idx
  on public.appointment_services (appointment_id);
create index if not exists booking_requests_date_idx
  on public.booking_requests (appointment_date);
create unique index if not exists appointments_unique_date_time
  on public.appointments (appointment_date, appointment_time)
  where status <> 'cancelado';

alter table public.appointments enable row level security;
alter table public.appointment_services enable row level security;
alter table public.booking_requests enable row level security;

drop policy if exists "Clientes enviam solicitações de encaixe"
  on public.booking_requests;
create policy "Clientes enviam solicitações de encaixe"
on public.booking_requests
for insert
to anon, authenticated
with check (status = 'pendente');

create or replace function public.create_appointment_with_services(
  appointment_data jsonb,
  services_data jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_appointment public.appointments%rowtype;
begin
  if appointment_data is null then
    raise exception 'appointment_data é obrigatório';
  end if;

  if services_data is null
    or jsonb_typeof(services_data) <> 'array'
    or jsonb_array_length(services_data) = 0 then
    raise exception 'services_data deve conter pelo menos um serviço';
  end if;

  if coalesce(
    (appointment_data ->> 'reservation_policy_accepted')::boolean,
    false
  ) is not true then
    raise exception
      'É necessário aceitar a política de reserva para criar o agendamento';
  end if;

  insert into public.appointments (
    customer_name, phone, email, notes, appointment_date,
    appointment_time, end_time, status, payment_status,
    reservation_paid, image_authorization,
    reservation_policy_accepted, service_price,
    reservation_amount, remaining_amount, payment_proof,
    duration_minutes, total_duration_minutes
  )
  select
    payload.customer_name, payload.phone, payload.email, payload.notes,
    payload.appointment_date, payload.appointment_time, payload.end_time,
    payload.status, payload.payment_status, payload.reservation_paid,
    payload.image_authorization, payload.reservation_policy_accepted,
    payload.service_price, payload.reservation_amount,
    payload.remaining_amount, payload.payment_proof,
    payload.duration_minutes, payload.total_duration_minutes
  from jsonb_populate_record(
    null::public.appointments,
    appointment_data
  ) as payload
  returning * into created_appointment;

  insert into public.appointment_services (
    appointment_id, service_id, service_name, duration_minutes,
    service_price, reservation_amount
  )
  select
    created_appointment.id, service_payload.service_id,
    service_payload.service_name, service_payload.duration_minutes,
    service_payload.service_price, service_payload.reservation_amount
  from jsonb_populate_recordset(
    null::public.appointment_services,
    services_data
  ) as service_payload;

  return to_jsonb(created_appointment);
end;
$$;

revoke all on function public.create_appointment_with_services(jsonb, jsonb)
from public;
grant execute on function public.create_appointment_with_services(jsonb, jsonb)
to anon, authenticated;

do $migration$
begin
  if to_regprocedure('public.get_booked_times(date)') is null then
    execute $function$
      create function public.get_booked_times(target_date date)
      returns table (
        appointment_time text,
        duration_minutes integer
      )
      language sql
      stable
      security definer
      set search_path = public
      as $body$
        select
          appointment.appointment_time,
          coalesce(
            appointment.total_duration_minutes,
            appointment.duration_minutes
          )::integer
        from public.appointments as appointment
        where appointment.appointment_date = target_date
          and appointment.status <> 'cancelado'
        order by appointment.appointment_time;
      $body$
    $function$;
  end if;
end;
$migration$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;

insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
values (
  'payment-proofs',
  'payment-proofs',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Clientes enviam comprovantes" on storage.objects;
create policy "Clientes enviam comprovantes"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'payment-proofs'
  and name ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(png|jpe?g|pdf)$'
);
