create table if not exists public.services (
  id bigint generated by default as identity primary key,
  legacy_id integer unique,
  slug text not null unique,
  name text not null,
  category text not null,
  short_description text not null default '',
  full_description text not null default '',
  duration_label text not null default '',
  duration_minutes integer not null check (duration_minutes > 0),
  price numeric(10,2) not null default 0 check (price >= 0),
  reservation_amount numeric(10,2) not null default 0 check (reservation_amount >= 0),
  is_active boolean not null default true,
  is_featured boolean not null default false,
  display_order integer not null default 0 check (display_order >= 0),
  card_title text,
  subtitle text,
  important_information text,
  payment_notice text not null default 'Aceitamos Pix, cartão de débito e cartão de crédito.',
  credit_card_fee_notice text not null default 'Pagamentos realizados no cartão de crédito estarão sujeitos à taxa da maquininha.',
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.services enable row level security;
drop policy if exists "Public can view active services" on public.services;
create policy "Public can view active services" on public.services for select
using (is_active or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Admins can manage services" on public.services;
create policy "Admins can manage services" on public.services for all to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

insert into public.services
  (legacy_id, slug, name, category, short_description, full_description, duration_label, duration_minutes, price, reservation_amount, is_active, is_featured, display_order)
values
  (1,'design-personalizado','Design Personalizado','Sobrancelhas','Design realizado de acordo com o formato do rosto para valorizar a expressão natural.','Design realizado de acordo com o formato do rosto para valorizar a expressão natural.','40 minutos',40,30,10,true,true,1),
  (2,'design-com-henna','Design com Henna','Sobrancelhas','Design de sobrancelhas com aplicação de henna para realçar o formato.','Design de sobrancelhas com aplicação de henna para realçar o formato e preencher visualmente pequenas falhas.','50 minutos',50,45,15,true,false,2),
  (3,'brow-lamination-sem-tintura','Brow Lamination sem Tintura','Sobrancelhas','Organiza e alinha os fios das sobrancelhas.','Procedimento que organiza e alinha os fios das sobrancelhas, proporcionando uma aparência mais definida.','1 hora',60,80,30,true,false,3),
  (4,'brow-lamination-com-tintura','Brow Lamination com Tintura','Sobrancelhas','Alinhamento dos fios combinado com tintura.','Alinhamento dos fios das sobrancelhas combinado com tintura para intensificar a definição.','1h20',80,100,35,true,false,4),
  (5,'microblading','Microblading','Micropigmentação','Procedimento semipermanente com resultado natural.','Procedimento semipermanente que proporciona sobrancelhas naturais e bem definidas.','1h40',100,280,50,true,true,5),
  (6,'extensao-de-cilios','Extensão de Cílios','Cílios','Alongamento dos fios para um olhar marcante.','Alongamento dos fios para proporcionar um olhar marcante, elegante e natural.','3 horas',180,125,30,true,true,6),
  (7,'manutencao-de-cilios','Manutenção de Cílios','Cílios','Reposição de fios para preservar o resultado.','Manutenção dos fios da extensão para repor perdas e preservar o resultado do procedimento.','2 horas',120,90,30,true,false,7),
  (8,'epilacao-facial','Epilação Facial','Cuidados Faciais','Remoção cuidadosa dos pelos faciais.','Remoção cuidadosa dos pelos faciais para proporcionar uma aparência mais uniforme.','40 minutos',40,55,20,true,false,8),
  (9,'epilacao-no-buco','Epilação no Buço','Cuidados Faciais','Remoção cuidadosa dos pelos da região do buço.','Remoção dos pelos da região do buço realizada de maneira cuidadosa.','10 minutos',10,20,10,true,false,9)
on conflict (slug) do nothing;

create table if not exists public.gallery_media (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  public_url text not null,
  media_type text not null check (media_type in ('photo','video')),
  title text not null,
  category text not null default 'Resultados',
  alt_text text not null default '',
  display_order integer not null default 0 check (display_order >= 0),
  is_active boolean not null default true,
  is_featured boolean not null default false,
  preferred_position text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gallery_media enable row level security;
drop policy if exists "Public can view active gallery media" on public.gallery_media;
create policy "Public can view active gallery media" on public.gallery_media for select
using (is_active or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Admins can manage gallery media" on public.gallery_media;
create policy "Admins can manage gallery media" on public.gallery_media for all to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('gallery-media','gallery-media',true,83886080,array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view gallery files" on storage.objects;
create policy "Public can view gallery files" on storage.objects for select
using (bucket_id = 'gallery-media');
drop policy if exists "Admins can upload gallery files" on storage.objects;
create policy "Admins can upload gallery files" on storage.objects for insert to authenticated
with check (bucket_id = 'gallery-media' and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Admins can update gallery files" on storage.objects;
create policy "Admins can update gallery files" on storage.objects for update to authenticated
using (bucket_id = 'gallery-media' and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
drop policy if exists "Admins can delete gallery files" on storage.objects;
create policy "Admins can delete gallery files" on storage.objects for delete to authenticated
using (bucket_id = 'gallery-media' and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
