create extension if not exists pgcrypto;

alter table public.appointments
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by text,
  add column if not exists late_cancellation boolean not null default false,
  add column if not exists reason text,
  add column if not exists cancellation_token uuid not null default gen_random_uuid();

create unique index if not exists appointments_cancellation_token_key
on public.appointments (cancellation_token);

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  appointment_id text,
  type text not null,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.admin_notifications enable row level security;

drop policy if exists "Admins can view notifications"
on public.admin_notifications;

create policy "Admins can view notifications"
on public.admin_notifications
for select
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
);

create or replace function public.get_cancellation_details(
  target_appointment_id text,
  cancellation_access_token uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  customer_email text;
  appointment_record public.appointments%rowtype;
  service_names text;
  starts_at timestamp;
begin
  customer_email := auth.jwt() ->> 'email';

  select *
  into appointment_record
  from public.appointments
  where id::text = target_appointment_id
    and (
      (customer_email is not null and lower(email) = lower(customer_email))
      or cancellation_token = cancellation_access_token
    );

  if not found then
    raise exception 'Agendamento não encontrado ou acesso não autorizado.';
  end if;

  select string_agg(service_name, ', ' order by service_name)
  into service_names
  from public.appointment_services
  where appointment_id::text = target_appointment_id;

  starts_at := appointment_record.appointment_date
    + appointment_record.appointment_time::time;

  return jsonb_build_object(
    'id', appointment_record.id,
    'serviceName', coalesce(service_names, appointment_record.service_name),
    'date', appointment_record.appointment_date,
    'time', to_char(appointment_record.appointment_time::time, 'HH24:MI'),
    'reservationAmount', appointment_record.reservation_amount,
    'status', appointment_record.status,
    'canCancel', appointment_record.status <> 'cancelado'
      and starts_at at time zone 'America/Sao_Paulo' > now(),
    'alreadyCancelled', appointment_record.status = 'cancelado'
  );
end;
$$;

create or replace function public.cancel_customer_appointment(
  target_appointment_id text,
  cancellation_access_token uuid default null,
  cancellation_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  customer_email text;
  appointment_record public.appointments%rowtype;
  service_names text;
  cancellation_time timestamptz := now();
begin
  customer_email := auth.jwt() ->> 'email';

  select *
  into appointment_record
  from public.appointments
  where id::text = target_appointment_id
    and (
      (customer_email is not null and lower(email) = lower(customer_email))
      or cancellation_token = cancellation_access_token
    )
  for update;

  if not found then
    raise exception 'Agendamento não encontrado ou acesso não autorizado.';
  end if;

  if appointment_record.status = 'cancelado' then
    raise exception 'Este agendamento já foi cancelado.';
  end if;

  if (appointment_record.appointment_date
    + appointment_record.appointment_time::time)
    at time zone 'America/Sao_Paulo' <= now() then
    raise exception 'Este atendimento não pode mais ser cancelado pelo site.';
  end if;

  select string_agg(service_name, ', ' order by service_name)
  into service_names
  from public.appointment_services
  where appointment_id::text = target_appointment_id;

  update public.appointments
  set
    status = 'cancelado',
    cancelled_at = cancellation_time,
    cancelled_by = case
      when auth.uid() is not null then 'cliente_area'
      else 'cliente_link_email'
    end,
    late_cancellation = false,
    reason = nullif(trim(cancellation_reason), '')
  where id::text = target_appointment_id;

  insert into public.admin_notifications (
    appointment_id,
    type,
    title,
    message
  ) values (
    target_appointment_id,
    'appointment_cancelled',
    'Novo cancelamento recebido',
    format(
      '%s cancelou o atendimento do dia %s às %s. O horário foi liberado automaticamente.',
      appointment_record.customer_name,
      to_char(appointment_record.appointment_date, 'DD/MM/YYYY'),
      to_char(appointment_record.appointment_time::time, 'HH24:MI')
    )
  );

  return jsonb_build_object(
    'id', appointment_record.id,
    'customerName', appointment_record.customer_name,
    'email', appointment_record.email,
    'serviceName', coalesce(service_names, appointment_record.service_name),
    'date', appointment_record.appointment_date,
    'time', to_char(appointment_record.appointment_time::time, 'HH24:MI'),
    'cancelledAt', cancellation_time,
    'status', 'cancelado'
  );
end;
$$;

revoke all on function public.get_cancellation_details(text, uuid)
from public;
revoke all on function public.cancel_customer_appointment(text, uuid, text)
from public;

grant execute on function public.get_cancellation_details(text, uuid)
to anon, authenticated;
grant execute on function public.cancel_customer_appointment(text, uuid, text)
to anon, authenticated;
