create table if not exists public.financial_transactions (
 id uuid primary key default gen_random_uuid(), appointment_id uuid references public.appointments(id) on delete restrict,
 customer_id uuid references auth.users(id) on delete set null, transaction_type text not null check(transaction_type in('reservation','remaining_payment','partial_payment','adjustment','refund')),
 amount numeric(10,2) not null check(amount>=0), gross_amount numeric(10,2) not null check(gross_amount>=0), machine_fee numeric(10,2) not null default 0 check(machine_fee>=0),
 net_amount numeric(10,2) not null check(net_amount>=0), payment_method text check(payment_method in('pix','debit_card','credit_card','cash','other')),
 payment_status text not null default 'received' check(payment_status in('pending','received','refused','refunded')),
 received_at timestamptz, created_by uuid references auth.users(id) on delete set null, notes text, idempotency_key text unique,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists financial_one_reservation_per_appointment on public.financial_transactions(appointment_id) where transaction_type='reservation' and payment_status='received';
create index if not exists financial_transactions_received_idx on public.financial_transactions(received_at desc);

create table if not exists public.expenses (
 id uuid primary key default gen_random_uuid(), expense_date date not null, description text not null,
 category text not null check(category in('materials','supplies','maintenance','courses','marketing','fees','other')),
 amount numeric(10,2) not null check(amount>0), payment_method text, notes text, receipt_path text,
 is_recurring boolean not null default false, recurrence_type text check(recurrence_type is null or recurrence_type in('weekly','monthly','yearly')),
 created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create index if not exists expenses_date_idx on public.expenses(expense_date desc) where deleted_at is null;

create table if not exists public.financial_activity (
 id bigint generated by default as identity primary key, entity_type text not null, entity_id text not null,
 action text not null, details jsonb not null default '{}'::jsonb, performed_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);

alter table public.financial_transactions enable row level security;
alter table public.expenses enable row level security;
alter table public.financial_activity enable row level security;
drop policy if exists "Admins manage financial transactions" on public.financial_transactions;
create policy "Admins manage financial transactions" on public.financial_transactions for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins manage expenses" on public.expenses;
create policy "Admins manage expenses" on public.expenses for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins read financial activity" on public.financial_activity;
create policy "Admins read financial activity" on public.financial_activity for select to authenticated using(public.is_admin());

create or replace function public.sync_reservation_transaction()
returns trigger language plpgsql security definer set search_path=public as $$ begin
 if new.reservation_paid=true and coalesce(new.payment_status,'') in('aprovado','pago','approved') then
  insert into public.financial_transactions(appointment_id,customer_id,transaction_type,amount,gross_amount,net_amount,payment_method,payment_status,received_at,notes,idempotency_key)
  values(new.id,new.user_id,'reservation',coalesce(new.reservation_amount,0),coalesce(new.reservation_amount,0),coalesce(new.reservation_amount,0),'pix','received',coalesce(new.created_at,now()),'Taxa de reserva aprovada','reservation:'||new.id)
  on conflict(idempotency_key) do nothing;
 end if; return new;
end $$;
drop trigger if exists sync_reservation_finance on public.appointments;
create trigger sync_reservation_finance after insert or update of reservation_paid,payment_status on public.appointments for each row execute function public.sync_reservation_transaction();

insert into public.financial_transactions(appointment_id,customer_id,transaction_type,amount,gross_amount,net_amount,payment_method,payment_status,received_at,notes,idempotency_key)
select a.id,a.user_id,'reservation',coalesce(a.reservation_amount,0),coalesce(a.reservation_amount,0),coalesce(a.reservation_amount,0),'pix','received',coalesce(a.created_at,now()),'Taxa de reserva aprovada','reservation:'||a.id
from public.appointments a where a.reservation_paid=true and coalesce(a.payment_status,'') in('aprovado','pago','approved')
on conflict(idempotency_key) do nothing;

create or replace function public.admin_get_financial_data(date_from date,date_to date)
returns jsonb language plpgsql security definer set search_path=public as $$ declare result jsonb; begin
 if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if;
 select jsonb_build_object(
  'appointments',coalesce((select jsonb_agg(to_jsonb(a) order by a.appointment_date desc,a.appointment_time desc) from public.appointments a where a.appointment_date between date_from and date_to),'[]'::jsonb),
  'transactions',coalesce((select jsonb_agg(to_jsonb(t) order by t.received_at desc nulls last,t.created_at desc) from public.financial_transactions t where coalesce(t.received_at,t.created_at)::date between date_from and date_to),'[]'::jsonb),
  'expenses',coalesce((select jsonb_agg(to_jsonb(e) order by e.expense_date desc,e.created_at desc) from public.expenses e where e.deleted_at is null and e.expense_date between date_from and date_to),'[]'::jsonb),
  'services',coalesce((select jsonb_agg(to_jsonb(s)) from public.appointment_services s join public.appointments a on a.id=s.appointment_id where a.appointment_date between date_from and date_to),'[]'::jsonb)
 ) into result; return result;
end $$;

create or replace function public.admin_record_payment(payload jsonb)
returns uuid language plpgsql security definer set search_path=public as $$
declare a public.appointments%rowtype; received numeric; fee numeric; already numeric; balance numeric; result uuid; method text; kind text; begin
 if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if;
 select * into a from public.appointments where id=(payload->>'appointment_id')::uuid for update;
 if not found then raise exception 'Agendamento não encontrado'; end if;
 received=(payload->>'amount')::numeric; fee=coalesce(nullif(payload->>'machine_fee','')::numeric,0); method=payload->>'payment_method';
 if received<=0 or fee<0 or fee>received then raise exception 'Valores de pagamento inválidos'; end if;
 select coalesce(sum(amount),0) into already from public.financial_transactions where appointment_id=a.id and payment_status='received';
 balance=greatest(coalesce(a.service_price,0)-already,0);
 if received>balance and not coalesce((payload->>'allow_overpayment')::boolean,false) then raise exception 'O valor informado é maior que o saldo pendente'; end if;
 kind=case when received<balance then 'partial_payment' else 'remaining_payment' end;
 insert into public.financial_transactions(appointment_id,customer_id,transaction_type,amount,gross_amount,machine_fee,net_amount,payment_method,payment_status,received_at,created_by,notes,idempotency_key)
 values(a.id,a.user_id,kind,received,received,fee,received-fee,method,'received',coalesce((payload->>'received_at')::timestamptz,now()),auth.uid(),payload->>'notes',nullif(payload->>'idempotency_key','')) returning id into result;
 update public.appointments set remaining_amount=greatest(coalesce(service_price,0)-(already+received),0), status=case when already+received>=coalesce(service_price,0) then 'concluido' else status end where id=a.id;
 insert into public.financial_activity(entity_type,entity_id,action,details,performed_by) values('transaction',result::text,'payment_recorded',payload,auth.uid()); return result;
exception when unique_violation then raise exception 'Este pagamento já foi registrado'; end $$;

create or replace function public.admin_save_expense(payload jsonb,target_id uuid default null)
returns uuid language plpgsql security definer set search_path=public as $$ declare result uuid; begin
 if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if;
 if coalesce(payload->>'description','')='' or (payload->>'amount')::numeric<=0 then raise exception 'Preencha a despesa corretamente'; end if;
 if target_id is null then insert into public.expenses(expense_date,description,category,amount,payment_method,notes,is_recurring,recurrence_type,created_by) values((payload->>'expense_date')::date,payload->>'description',payload->>'category',(payload->>'amount')::numeric,nullif(payload->>'payment_method',''),nullif(payload->>'notes',''),coalesce((payload->>'is_recurring')::boolean,false),nullif(payload->>'recurrence_type',''),auth.uid()) returning id into result;
 else update public.expenses set expense_date=(payload->>'expense_date')::date,description=payload->>'description',category=payload->>'category',amount=(payload->>'amount')::numeric,payment_method=nullif(payload->>'payment_method',''),notes=nullif(payload->>'notes',''),is_recurring=coalesce((payload->>'is_recurring')::boolean,false),recurrence_type=nullif(payload->>'recurrence_type',''),updated_at=now() where id=target_id and deleted_at is null returning id into result; end if;
 insert into public.financial_activity(entity_type,entity_id,action,details,performed_by) values('expense',result::text,case when target_id is null then 'created' else 'updated' end,payload,auth.uid()); return result;
end $$;

create or replace function public.admin_delete_expense(target_id uuid)
returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'Acesso administrativo necessário'; end if; update public.expenses set deleted_at=now(),updated_at=now() where id=target_id; insert into public.financial_activity(entity_type,entity_id,action,performed_by) values('expense',target_id::text,'deleted',auth.uid()); end $$;

grant execute on function public.admin_get_financial_data(date,date) to authenticated;
grant execute on function public.admin_record_payment(jsonb) to authenticated;
grant execute on function public.admin_save_expense(jsonb,uuid) to authenticated;
grant execute on function public.admin_delete_expense(uuid) to authenticated;
