create table if not exists public.monthly_schedule_releases (
  id bigint generated by default as identity primary key,
  year integer not null check (year between 2020 and 2100),
  month integer not null check (month between 1 and 12),
  status text not null default 'draft' check (status in ('draft', 'released', 'closed')),
  blocked_dates date[] not null default '{}',
  special_hours jsonb not null default '{}',
  admin_notes text,
  released_at timestamptz,
  released_by uuid references auth.users(id),
  released_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (year, month)
);

alter table public.monthly_schedule_releases enable row level security;

insert into public.monthly_schedule_releases (year, month, status, released_at)
values (
  extract(year from (now() at time zone 'America/Sao_Paulo'))::integer,
  extract(month from (now() at time zone 'America/Sao_Paulo'))::integer,
  'released',
  now()
)
on conflict (year, month) do nothing;

drop policy if exists "Public can view released monthly schedules" on public.monthly_schedule_releases;
create policy "Public can view released monthly schedules"
on public.monthly_schedule_releases for select
using (
  status = 'released'
  or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
);

drop policy if exists "Admins manage monthly schedules" on public.monthly_schedule_releases;
create policy "Admins manage monthly schedules"
on public.monthly_schedule_releases for all to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin')
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');

create unique index if not exists admin_notifications_schedule_reminder_unique
on public.admin_notifications (type, ((created_at at time zone 'America/Sao_Paulo')::date))
where type like 'schedule_release_reminder_%';

create or replace function public.create_monthly_schedule_release_reminders()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  local_today date := (now() at time zone 'America/Sao_Paulo')::date;
  next_month date := (date_trunc('month', local_today) + interval '1 month')::date;
  reminder_type text;
  reminder_title text;
begin
  if extract(day from local_today) not in (20, 25)
     and local_today <> (date_trunc('month', local_today) + interval '1 month - 1 day')::date then
    return;
  end if;

  if exists (
    select 1 from public.monthly_schedule_releases
    where year = extract(year from next_month)::integer
      and month = extract(month from next_month)::integer
      and status = 'released'
  ) then
    return;
  end if;

  reminder_type := case
    when extract(day from local_today) = 20 then 'schedule_release_reminder_20'
    when extract(day from local_today) = 25 then 'schedule_release_reminder_25'
    else 'schedule_release_reminder_final'
  end;
  reminder_title := case
    when reminder_type = 'schedule_release_reminder_final' then 'Alerta prioritário: agenda ainda fechada'
    else 'Lembrete: libere a agenda de ' || case extract(month from next_month)::integer
      when 1 then 'janeiro' when 2 then 'fevereiro' when 3 then 'março'
      when 4 then 'abril' when 5 then 'maio' when 6 then 'junho'
      when 7 then 'julho' when 8 then 'agosto' when 9 then 'setembro'
      when 10 then 'outubro' when 11 then 'novembro' else 'dezembro'
    end
  end;

  insert into public.admin_notifications (type, title, message)
  values (
    reminder_type,
    reminder_title,
    'A agenda do próximo mês ainda não está disponível para as clientes.'
  )
  on conflict do nothing;
end;
$$;

revoke all on function public.create_monthly_schedule_release_reminders() from public;

do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    if not exists (select 1 from cron.job where jobname = 'monthly-schedule-release-reminders') then
      perform cron.schedule(
        'monthly-schedule-release-reminders',
        '15 9 * * *',
        'select public.create_monthly_schedule_release_reminders();'
      );
    end if;
  end if;
exception when others then
  raise notice 'pg_cron não pôde ser configurado automaticamente: %', sqlerrm;
end $$;
